#!/usr/bin/env python3
"""Port the already-written labhandbook nodes that answer a sheet question.

Re-runnable: rebuilds data/ch1.js .. ch3.js from scratch, so a fix made upstream
propagates by running this again. Nodes written directly for this app must NOT
live in these files -- put them in ch1b.js, ch2b.js and add a script tag.

Cross-references are remapped from the PORT table rather than from a hand-written
list. An earlier version listed them by hand, and missed two the moment the port
set grew: the list had been grepped out of ch5.js only. Anything derived from the
table cannot drift out of step with it.
"""
import os, re

# This app lives in the bio-state-exam repo; labhandbook lives in the
# recombinants repo. Absolute and explicit, because the relative path this
# replaced pointed at a directory that does not exist from here.
TRAE = 'C:/Users/Admin/Documents/trae_projects/recombinants_trae_independant'
SRC = os.path.join(TRAE, 'labhandbook', 'data')
DST = 'data'

# Second source root. The §9 sheet-question layer assembles a model answer by
# walking a `spine` of node ids and pulling each node's own mustKnow, so every
# id a question cites has to resolve INSIDE this app. The first question entry
# cited eight pesbexplain nodes that were never ported, so the spine resolved to
# an empty array and the answer rendered blank while the panel still looked
# populated -- see handoff §13. These are those nodes.
PESB_SRC = os.path.join(TRAE, 'pesbexplain', 'data')

# labhandbook id -> (exambank id, chapter, lecture, section)
PORT = {
    '5-1': ('1-1', 1, 'Lab',     '1.1'),   # standard solution / curve / molarity
    '4-1': ('1-2', 1, 'Lab',     '1.2'),   # pH and pKa
    '4-2': ('1-3', 1, 'Lab',     '1.3'),   # buffers, the Tris paradox
    '4-3': ('1-4', 1, 'Lab',     '1.4'),   # glass electrode, calibration
    '3-2': ('1-5', 1, 'Lab',     '1.5'),   # BCA, and the standard curve again
    '5-3': ('2-1', 2, 'Micro',   '2.1'),   # isolating and culturing bacteria
    '5-2': ('3-1', 3, 'Biochem', '3.1'),   # fitness vs folding landscape
    '4-4': ('3-2', 3, 'Biochem', '3.2'),   # lac operon mirrored against GAL1
}

# pesbexplain id -> (exambank id, chapter, lecture, section). Emitted to ch1c.js.
# Chapter 1 because the question these answer is S1 Lab 3, a Lab question; they
# are the reference layer a spine walks, not sheet answers in their own right,
# so none of them carries a `slides` sheet ref and none counts as coverage.
#
# Kept in spine order, which is the order the model answer is spoken in.
PESB_PORT = {
    '2-4':  ('1-9',  1, 'Expr', '1.9'),    # why E. coli is still the default
    '2-6':  ('1-10', 1, 'Expr', '1.10'),   # getting DNA in: chemical vs electroporation
    '2-7':  ('1-11', 1, 'Expr', '1.11'),   # promoters: strength vs tightness
    '2-8':  ('1-12', 1, 'Expr', '1.12'),   # the T7 / DE3 two-step architecture
    '2-9':  ('1-13', 1, 'Expr', '1.13'),   # induction, IPTG, autoinduction
    '2-10': ('1-14', 1, 'Expr', '1.14'),   # inclusion bodies are not a failure
    '2-26': ('1-15', 1, 'Expr', '1.15'),   # cell disruption
    '2-29': ('1-16', 1, 'Expr', '1.16'),   # chromatography fundamentals
}

# Prose citations. These carry surrounding words, so they cannot be rewritten by
# the same mechanism as optionRefs -- "see 4-1" must not match "chapters 1-4".
# Each entry is asserted to fire exactly once.
PROSE_REFS = [
    # Capitalised because upstream reworded it to start a sentence. The
    # never-fired assertion below caught the lowercase form going stale the
    # moment that happened, which is the whole point of keeping the guard.
    ('See 4-1 ',                                  'See 1-2 '),
    ('and 4-3 for',                               'and 1-4 for'),
    ('This is node 4-1 in a different costume',   'This is node 1-2 in a different costume'),
    ('这是 4-1 节换了身衣服',                       '这是 1-2 节换了身衣服'),
    # Upstream can only say Lambert-Beer is uncovered, because in labhandbook it
    # is. This app DOES cover it, in 1-8, so the ported text points there. Keep
    # this in step with 5-1's coverageNote or the sentence contradicts itself.
    ('Lambert-Beer itself is NOT covered here, and a ',
     'Lambert-Beer is covered in node 1-8 of this app, not here; upstream it is '
     'uncovered and a '),
]

CH_TITLES = {1: 'Basic Lab Techniques', 2: 'Microbiology', 3: 'Biochemistry'}

PESB_HEADER = """/* =========================================================================
   EXAM BANK — Chapter 1c . Ported from pesbexplain

   GENERATED by tools/port.py (port_pesb) — do not hand-edit this file.

   These are NOT sheet answers and none of them carries a sheet ref, so none
   counts towards question coverage. They are the reference layer the §9
   sheet-question spines walk: a question entry names an ordered list of node
   ids and app.js assembles the model answer from each node's own mustKnow, so
   every id a question cites has to resolve inside this app.

   Before this file existed, the only question entry cited eight pesbexplain
   ids that were never ported. The spine resolved to an empty array, no model
   answer was assembled, and the panel still rendered stem, joins and
   follow-ups — so it looked answered while being blank. See handoff §13.

   Ids are remapped through PESB_PORT, on an idmap kept separate from the
   labhandbook one because both corpora contain a node called '4-1'.
   ========================================================================= */

window.PESB = window.PESB || {};
window.PESB.topics = (window.PESB.topics || []).concat([
"""

HEADER = """/* =========================================================================
   EXAM BANK — Chapter {ch} . {title}

   GENERATED by tools/port.py — do not hand-edit this file.
   Every node here was already written in ../labhandbook and answers a question
   printed on one of the supervisor's three sheets. Porting rather than
   rewriting is what SCOPE.md means by importing the neighbouring corpora: the
   facts were verified there, and re-typing them would only add a chance to get
   one wrong. Node ids and cross-references are remapped; nothing else changes.

   Nodes written directly for this app go in ch{ch}b.js, not here.
   ========================================================================= */

window.PESB = window.PESB || {{}};
window.PESB.topics = (window.PESB.topics || []).concat([
"""


def load_nodes(src=SRC):
    """{upstream_id: node_source} for every node in every chapter file under src."""
    nodes = {}
    for fn in sorted(os.listdir(src)):
        if not (fn.startswith('ch') and fn.endswith('.js')):
            continue
        s = open(os.path.join(src, fn), encoding='utf-8').read()
        # A non-greedy match to the first "\n}\n" stops INSIDE a node, because
        # nested objects close the same way. Slice on the node starts instead.
        starts = [m.start() for m in re.finditer(r"\n\{\n  id: '", s)]
        for i, a in enumerate(starts):
            b = starts[i + 1] if i + 1 < len(starts) else s.rindex('\n]);')
            body = s[a:b].strip()
            # labhandbook packs nodes back to back, so stripping one trailing
            # comma was enough. pesbexplain puts section banners between them
            # -- "/* ===== PART I ===== */" -- which land inside this slice and
            # leave it ending in a comment rather than in '}'. Cut back to the
            # node's own closing brace, which is the last one at column 0.
            end = body.rfind('\n}')
            if end != -1:
                body = body[:end + 2]
            assert body.startswith('{') and body.endswith('}'), '%s node %d bad slice' % (fn, i)
            nodes[re.search(r"id: '([^']+)'", body).group(1)] = body
    return nodes


def remap_fields(body, new_id, chapter, lecture, section):
    for pat, rep in ((r"^  id: '[^']+',",      "  id: '%s'," % new_id),
                     (r"^  chapter: \d+,",     "  chapter: %d," % chapter),
                     (r"^  lecture: '[^']*',", "  lecture: '%s'," % lecture),
                     (r"^  section: '[^']*',", "  section: '%s'," % section)):
        body, n = re.subn(pat, rep, body, count=1, flags=re.M)
        assert n == 1, 'field %s not found in %s' % (pat, new_id)
    return body


def remap_option_refs(body, own_id, idmap, dropped):
    """Rewrite every optionRefs id through idmap; drop any that cannot resolve.

    A ref to a node that was not ported would dangle, and a ref that lands on the
    node's own id breaks authoring rule 8. Both are dropped and reported rather
    than silently left in.
    """
    def fix_block(m):
        entries = []
        for key, ref in re.findall(r"(\d+)\s*:\s*'([^']+)'", m.group(1)):
            new = idmap.get(ref)
            if new is None or new == own_id:
                dropped.append((own_id, ref, 'unported' if new is None else 'self'))
                continue
            entries.append("%s: '%s'" % (key, new))
        if not entries:
            return '__DROP_OPTIONREFS__'
        return 'optionRefs: { %s }' % ', '.join(entries)

    body = re.sub(r"optionRefs: \{([^}]*)\}", fix_block, body)
    # a dropped block leaves a dangling line; remove the whole line and any
    # comma the previous line used to need
    body = re.sub(r",\n(\s*)__DROP_OPTIONREFS__", "", body)
    body = re.sub(r"\n\s*__DROP_OPTIONREFS__,?", "", body)
    assert '__DROP_OPTIONREFS__' not in body, 'could not remove a dropped optionRefs in %s' % own_id
    return body


def main():
    nodes = load_nodes()
    assert nodes, 'no nodes parsed out of %s — the node format changed' % SRC
    missing = sorted(set(PORT) - set(nodes))
    assert not missing, 'PORT names nodes that do not exist upstream: %s' % missing

    idmap = {src: dst[0] for src, dst in PORT.items()}
    new_ids = set(idmap.values())
    assert len(new_ids) == len(PORT), 'PORT maps two upstream nodes onto one new id'

    prose_hits = {old: 0 for old, _ in PROSE_REFS}
    dropped = []
    by_chapter = {}

    for src_id, (new_id, ch, lec, sec) in PORT.items():
        body = remap_fields(nodes[src_id], new_id, ch, lec, sec)
        for old, new in PROSE_REFS:
            if old in body:
                prose_hits[old] += body.count(old)
                body = body.replace(old, new)
        body = remap_option_refs(body, new_id, idmap, dropped)
        by_chapter.setdefault(ch, []).append((new_id, body))

    written = {}
    for ch, items in sorted(by_chapter.items()):
        items.sort(key=lambda t: [int(x) for x in t[0].split('-')])
        out = HEADER.format(ch=ch, title=CH_TITLES[ch])
        out += '\n' + ',\n\n'.join(b for _, b in items) + '\n\n]);\n'
        path = os.path.join(DST, 'ch%d.js' % ch)
        open(path, 'w', encoding='utf-8', newline='\n').write(out)
        written[path] = [nid for nid, _ in items]

    # ---- assertions on our own output ------------------------------------
    unfired = [o for o, n in prose_hits.items() if n == 0]
    assert not unfired, ('these prose citations never fired, so they were reworded '
                         'upstream and the port is now silently wrong: %s' % unfired)

    total = sum(len(v) for v in written.values())
    assert total == len(PORT), 'wrote %d nodes, PORT lists %d' % (total, len(PORT))

    for path, ids in sorted(written.items()):
        s = open(path, encoding='utf-8').read()
        assert s.rstrip().endswith(']);'), '%s does not close' % path
        assert s.count("\n  id: '") == len(ids), '%s: id count != node count' % path
        for ref in re.findall(r"optionRefs: \{([^}]*)\}", s):
            for _, rid in re.findall(r"(\d+)\s*:\s*'([^']+)'", ref):
                assert rid in new_ids, '%s: optionRef %s resolves to nothing' % (path, rid)
        print('%-14s %d nodes  %7d chars   %s' % (path, len(ids), len(s), ' '.join(ids)))

    for own, ref, why in dropped:
        print('  dropped optionRef %s -> %s (%s)' % (own, ref, why))
    print('prose citations rewritten: %d' % sum(prose_hits.values()))

    port_pesb()
    print('RESULT: PASS')


def port_pesb():
    """Port the pesbexplain nodes cited by a §9 question spine, into ch1c.js.

    Deliberately a separate pass with its OWN idmap. Sharing the labhandbook
    idmap would be a live correctness bug rather than a tidiness one: both
    corpora contain a node called '4-1', so a pesbexplain optionRef to '4-1'
    would silently be rewritten to labhandbook 4-1's destination. Keeping the
    maps apart means a cross-corpus ref cannot resolve at all, and therefore
    gets dropped and reported instead of landing on the wrong node.

    PROSE_REFS is likewise not applied here -- those strings were written
    against labhandbook prose.
    """
    nodes = load_nodes(PESB_SRC)
    assert nodes, 'no nodes parsed out of %s -- the node format changed' % PESB_SRC
    missing = sorted(set(PESB_PORT) - set(nodes))
    assert not missing, 'PESB_PORT names nodes that do not exist upstream: %s' % missing

    idmap = {src: dst[0] for src, dst in PESB_PORT.items()}
    new_ids = set(idmap.values())
    assert len(new_ids) == len(PESB_PORT), 'PESB_PORT maps two upstream nodes onto one new id'

    dropped = []
    items = []
    for src_id, (new_id, ch, lec, sec) in PESB_PORT.items():
        body = remap_fields(nodes[src_id], new_id, ch, lec, sec)
        body = remap_option_refs(body, new_id, idmap, dropped)
        items.append((new_id, body))

    items.sort(key=lambda t: [int(x) for x in t[0].split('-')])
    out = PESB_HEADER
    out += '\n' + ',\n\n'.join(b for _, b in items) + '\n\n]);\n'
    path = os.path.join(DST, 'ch1c.js')
    open(path, 'w', encoding='utf-8', newline='\n').write(out)

    s = open(path, encoding='utf-8').read()
    assert s.rstrip().endswith(']);'), '%s does not close' % path
    assert s.count("\n  id: '") == len(items), '%s: id count != node count' % path
    for ref in re.findall(r"optionRefs: \{([^}]*)\}", s):
        for _, rid in re.findall(r"(\d+)\s*:\s*'([^']+)'", ref):
            assert rid in new_ids, '%s: optionRef %s resolves to nothing' % (path, rid)

    # Every node here exists to be walked by a spine, so mustKnow is the one
    # field that must survive the port -- an empty one renders a blank beat.
    for nid, body in items:
        assert re.search(r"^  mustKnow: '", body, re.M), '%s lost its mustKnow' % nid

    print('%-14s %d nodes  %7d chars   %s'
          % (path, len(items), len(s), ' '.join(nid for nid, _ in items)))
    for own, ref, why in dropped:
        print('  dropped optionRef %s -> %s (%s)' % (own, ref, why))


if __name__ == '__main__':
    main()
