/* Pre-rendered reading audio for the 速通简洁版. Generated by
   tools/render-spine-audio.py — do not edit by hand.

   Maps fnv1a32(lang + U+001F + normalised text) to a file in this folder,
   the same scheme the full app uses. The app hashes the text it would have
   spoken and plays the file if there is one; otherwise it falls back to the
   browser's own voice, which is what every clip-less button does anyway.

   Separate global from the full app's on purpose: the two say different
   things, and one shared name would have whichever loaded last win.

   Voice: Kokoro-82M (Apache-2.0). That licence is why this audio can be
   committed and served publicly. */
window.BIOLITE_AUDIO = {
"0161dcca": "0161dcca.m4a",
"057d101b": "057d101b.m4a",
"0b65225a": "0b65225a.m4a",
"0e486e09": "0e486e09.m4a",
"0eac6212": "0eac6212.m4a",
"1624a5dc": "1624a5dc.m4a",
"18fca79d": "18fca79d.m4a",
"24097bfa": "24097bfa.m4a",
"30d7e8db": "30d7e8db.m4a",
"31b07f50": "31b07f50.m4a",
"3338b98e": "3338b98e.m4a",
"38071517": "38071517.m4a",
"3a0fc838": "3a0fc838.m4a",
"3f8c404a": "3f8c404a.m4a",
"428a62a4": "428a62a4.m4a",
"5660e2e9": "5660e2e9.m4a",
"56b1b4d8": "56b1b4d8.m4a",
"598d354e": "598d354e.m4a",
"5b12ab02": "5b12ab02.m4a",
"5efcd027": "5efcd027.m4a",
"643348e3": "643348e3.m4a",
"65128e8e": "65128e8e.m4a",
"66e36da2": "66e36da2.m4a",
"67b81cea": "67b81cea.m4a",
"6959794c": "6959794c.m4a",
"6bbcd954": "6bbcd954.m4a",
"6c7a8b3b": "6c7a8b3b.m4a",
"6cf2a1dd": "6cf2a1dd.m4a",
"8c6b6740": "8c6b6740.m4a",
"947d13b1": "947d13b1.m4a",
"96008122": "96008122.m4a",
"9676c691": "9676c691.m4a",
"a1f9f231": "a1f9f231.m4a",
"a470bd7a": "a470bd7a.m4a",
"a5b25da2": "a5b25da2.m4a",
"a93bff1d": "a93bff1d.m4a",
"b19bbdc7": "b19bbdc7.m4a",
"b2e0c5f7": "b2e0c5f7.m4a",
"bd45f191": "bd45f191.m4a",
"bf7e8abc": "bf7e8abc.m4a",
"c51fb956": "c51fb956.m4a",
"c9999341": "c9999341.m4a",
"cc59a7ef": "cc59a7ef.m4a",
"d13bcba1": "d13bcba1.m4a",
"d83465c7": "d83465c7.m4a",
"dc7a5f8d": "dc7a5f8d.m4a",
"e7245f25": "e7245f25.m4a",
"f2889e4a": "f2889e4a.m4a",
"f4a58648": "f4a58648.m4a",
"f79f90ca": "f79f90ca.m4a",
"f949e9f5": "f949e9f5.m4a",
"f9eb5fc2": "f9eb5fc2.m4a",
"fa965706": "fa965706.m4a",
"fae0b28a": "fae0b28a.m4a",
"fb9458e4": "fb9458e4.m4a"
};
