# -*- coding: utf-8 -*-
"""人工补的中文释义 —— 词典和她的词库都没有的那些。

起因 2026-09-15 Ruojin：「你现在弄的所有单词 把他们的中文释义也加上」。

自动那三层（她的生化词库 → 通用英汉词典 → 连字符自动拼）走完之后还剩两百多个，
分三类，这张表负责其中该写的那些：

  1. 真术语      aconitate、calreticulin、oligosaccharyltransferase、semidiscontinuous…
  2. 人名菌名    Blobel、Chargaff、Meselson、Thermus、subtilis、Kapa —— 写「他是谁 / 它是什么」，
                 不写「一个姓氏」。她需要的是「Blobel＝提出信号肽假说的人」。
  3. 符号片段    Mg、Zn、S-S、CO-NH、EC、SAM、BCAA、Svedberg —— 这些不是英语单词，
                 但点到了就该给个说法。

**不写的**：捷克语残留（amfipatie、izomerace、sacharosa…）——那是卡上还没清干净的捷克语，
等清完这些词自己就消失了，别在这儿给它们编中文。
以及纯序列（cgcatgcg）和拆碎的化学式（e-o-co-ch），给不出有意义的说法就留空。

格式：键是小写词形，值是 (中文, 英文释义或空字符串)。
中文尽量写成**一句能懂的话**，不是一个对译词——她要的是看懂，不是查到。

这张表优先级最高，排在她的词库和通用词典前面。加完跑：
    python tools/make_gloss.py
"""

EXTRA = {
    # 她旧词库里 biology 那条是一段课程介绍，不是释义。
    'biology': ('生物学 —— 研究生命体及其过程的科学。', 'The study of living organisms and their processes.'),

    # 这两个不是捷克语残留，清完捷克语也不会消失，所以照写。
    'eikosi': ('希腊语的「二十」。二十碳酸（eicosanoid，类二十烷酸）就是照这个数命名的——'
               '前体花生四烯酸正好二十个碳。卡 23 和卡 32 里用英文讲过这个词源。', 'Greek for twenty'),
    'obr': ('捷克语 Obr. ＝「图」，书里图注的开头。卡上的中文页码引用里还留着这个写法，'
            '比如 Obr. 4.8 就是书第 73 页那张 B-DNA 的图。', 'Czech abbreviation for figure'),


# ---------------- 1 · 真术语 ----------------

'aconitate': ('乌头酸。柠檬酸循环第二步的中间体：柠檬酸先脱一分子水变成顺乌头酸（cis-aconitate），再加水变成异柠檬酸，两步都由 aconitase 催化。书把这一脱一加算作两个反应，所以它管「顺乌头酸加水」叫第三反应。',
              'cis-aconitate: the dehydrated intermediate between citrate and isocitrate, both steps on aconitase.'),
'adp-forming': ('（生成 ADP 的）。连接酶（ligase）系统命名末尾的括号项，写成「X : Y ligase (ADP-forming)」，意思是这个酶把 ATP 切成 ADP ＋ Pi 来出力；写 (AMP-forming) 就是切到 AMP ＋ PPi。',
                'The bracketed part of a ligase systematic name, saying which ATP cleavage it uses.'),
'atp-forming': ('产 ATP 的。糖酵解里指底物水平磷酸化那两步（1,3-二磷酸甘油酸→3-磷酸甘油酸，磷酸烯醇式丙酮酸→丙酮酸），每步给 ADP 一个磷酸。', ''),
'aldonic': ('醛糖酸的。糖的醛基（C-1）被氧化成羧基就得到 aldonic acid，例如葡萄糖→葡萄糖酸。对比：氧化末端的 CH₂OH 得到的是糖醛酸 uronic acid。',
            'Sugar acid made by oxidising the aldehyde at C-1.'),
'alkoxyl': ('烷氧基（RO–）。卡 06 用的就是这个意思：把半缩醛上的羟基换成一个烷氧基，就从半缩醛变成缩醛，也就是糖苷。另有一处指烷氧自由基 RO•。',
            'An RO- group; also the alkoxyl radical RO. in the free-radical list.'),
'aminolevulinate': ('δ-氨基乙酰丙酸（ALA）。血红素合成的第一个中间体：琥珀酰-CoA ＋ 甘氨酸→δ-氨基乙酰丙酸，这也是柠檬酸循环通向血红素的出口。', ''),
'anoic': ('-anoic，脂肪酸系统命名里表示「饱和」的后缀（octadecanoic acid ＝ 十八碳饱和酸）。有双键就换成 -enoic（一个）、-dienoic（两个）、-trienoic（三个）。', ''),
'enoic': ('-enoic，脂肪酸系统命名里表示「一个双键」的后缀（octadecenoic acid ＝ 十八碳一烯酸）。', ''),
'dienoic': ('-dienoic，脂肪酸系统命名里表示「两个双键」的后缀，例如亚油酸 octadecadienoic acid。', ''),
'trienoic': ('-trienoic，脂肪酸系统命名里表示「三个双键」的后缀，例如 α-亚麻酸 octadecatrienoic acid。', ''),
'antithrombin': ('抗凝血酶（antithrombin III）。血浆里的蛋白酶抑制剂，专门灭活凝血酶；肝素就是结合它、把它的速度放大上千倍，所以肝素是抗凝剂。',
                 'The plasma inhibitor of thrombin that heparin binds and accelerates.'),
'archaeal': ('古菌的。卡上指 PCR 用的高保真酶：那些带校对活性的聚合酶属于 B 家族，来源是古菌（如 Pfu），跟 Taq 的 A 家族不是一路。', ''),
'autoionises': ('自偶电离。指水自己分解出一点 H⁺ 和 OH⁻（2 H₂O ⇌ H₃O⁺ ＋ OH⁻），这是 pH 标度和 Kw ＝ 10⁻¹⁴ 的来源。', ''),
'autoradiogram': ('放射自显影图。把放射性标记的分子压在感光胶片上得到的影像。卡 16 指 Cairns 用氚标胸苷做出的那张大肠杆菌复制中染色体的图。',
                  'An image made by laying radioactively labelled material on photographic film.'),
'base-pairing': ('碱基配对（A–T、G–C）。书说复制的第一道纠错就是碱基配对本身，聚合酶的校对是第二道。', ''),
'beta-hydroxyacyl-coa': ('β-羟脂酰-CoA。脂肪酸 β 氧化第三步的底物：加水之后得到它，再由 β-羟脂酰-CoA 脱氢酶用 NAD⁺ 把羟基氧化成酮基。', ''),
'biomolecule': ('生物分子。卡 23 那句的重点是：脂类是唯一一类不是聚合物的生物大分子。', ''),
'c-propeptide': ('C 端前肽。前胶原两端各有一段前肽，C 端那一段负责把三条 α 链对齐、拉到一起并形成链间二硫键，三股螺旋随后从 C 端往 N 端拉起；分泌到细胞外后被前肽酶切掉。',
                 'The C-terminal propeptide that aligns the three procollagen chains and forms interchain disulfides.'),
'c-propeptides': ('C 端前肽（复数）。见 c-propeptide：procollagen 的 N 端和 C 端各有一段前肽，分泌后被切掉才成为 collagen。', ''),
'c-rich': ('富含胞嘧啶的。卡上出现的是 G+C-rich：GC 含量高的那段回文，转录出来能折成稳定发夹，是不依赖 rho 的终止子。', ''),
'caeruloplasmin': ('铜蓝蛋白。血浆里运铜的蛋白，跟运铁的转铁蛋白（transferrin）成对出现在书的例子里。',
                   'The plasma copper-carrying protein, paired with transferrin for iron.'),
'calnexin': ('钙连蛋白。内质网里的凝集素样伴侣蛋白，抓住新生糖蛋白核心上的那一个葡萄糖，把它留在折叠循环里；它是膜结合的，可溶的同伙叫 calreticulin。',
             'ER lectin chaperone (membrane-bound) of the calnexin/calreticulin folding cycle.'),
'calreticulin': ('钙网蛋白。内质网腔里可溶的凝集素样伴侣蛋白，和膜上的 calnexin 干同一件事：认糖基化核心上剩下的那个葡萄糖，把没折好的糖蛋白留在循环里（UGGT 再加回一个葡萄糖就再来一轮）。',
                 'The soluble ER counterpart of calnexin in the glycoprotein folding cycle.'),
'carboxyglutamate': ('γ-羧基谷氨酸（Gla）。维生素 K 依赖的羧化酶在谷氨酸侧链的 γ 碳上再加一个羧基，两个羧基一起螯合 Ca²⁺，凝血因子靠它挂到膜上——这就是维生素 K 和凝血的连接点。', ''),
'carboxylic': ('羧酸的（–COOH）。acyl 基就是羧酸拿掉 OH 剩下的部分；酰基磷酸（如 1,3-二磷酸甘油酸的 C-1）就是羧酸和磷酸的酸酐。', ''),
'chiral': ('手性的。一个碳上接四个不同基团，镜像不能重合。二十种氨基酸里只有甘氨酸不是手性的（它的 α 碳上有两个氢）。',
           'Having a non-superimposable mirror image; an asymmetric centre.'),
'cisternae': ('（内质网的）腔、潴泡。cisterna 的复数。卡上说胶原的羟化、二硫键的形成和重排都发生在内质网腔里。', ''),
'citryl-coa': ('柠檬酰-CoA。柠檬酸合酶反应的中间体：乙酰-CoA 的 α 碳进攻草酰乙酸的羰基碳（书叫它 aldol condensation），先得到还带着 CoA 的柠檬酰-CoA，再水解掉硫酯键放出柠檬酸——正是这一步水解把反应拉到不可逆。', ''),
'claisen-type': ('Claisen 型（酯缩合）。指碳负离子被相邻硫酯的羰基稳住的那种缩合。Lehninger 把柠檬酸合酶那一步叫 Claisen-type condensation，因为进攻的是硫酯的烯醇负离子；捷克书叫它 aldol condensation。', ''),
'convertases': ('转化酶（prohormone convertases）。切前激素的那类蛋白酶，在特定的碱性氨基酸对处下刀，和羧肽酶 E 一起把 proinsulin 这类前体加工成成熟激素。', ''),
'crassulacean': ('景天科的。CAM 全称 crassulacean acid metabolism（景天酸代谢），因为最早在景天科的多肉植物里发现：夜里开气孔固定 CO₂ 存成苹果酸，白天关气孔再脱羧放出来。', ''),
'cyclisation': ('环化。单糖的开链形式里，羟基进攻自己的羰基成环（半缩醛/半缩酮）。书的原话是：环化时 C-1 变成一个新的不对称碳，所以有 α、β 两种环形，这就是异头碳和变旋。', ''),
'cysteic': ('半胱磺酸（cysteic acid）。做氨基酸组成分析时用过甲酸把二硫键彻底氧化开，产物就是它——这是不可逆的那条路；可逆的那条是用还原剂变回两个半胱氨酸。', ''),
'd-fructofuranosidase': ('β-D-呋喃果糖苷酶，也就是转化酶（invertase）。从果糖那一端切蔗糖，得到游离葡萄糖和游离果糖——蜂蜜比蔗糖甜就是因为蔗糖被它水解了。', ''),
'decarboxylate': ('脱羧：把一个羧基以 CO₂ 的形式甩掉。CAM 植物白天做的就是这件事。', ''),
'decarboxylated': ('被脱羧的 / 已脱羧。丙酮酸被「氧化脱羧」成乙酰-CoA，就是既掉 CO₂ 又被氧化。', ''),
'decarboxylates': ('脱羧（第三人称）。β-氧代酸（酮基在 β 位）特别容易自发脱羧，这是很多代谢步骤走得动的原因。', ''),
'decarboxylating': ('脱羧的。卡 28 里 decarboxylating malate dehydrogenase（脱羧苹果酸脱氢酶，书也叫苹果酸酶）一步既氧化又脱羧，交出 CO₂ 和一分子 NADPH。', ''),
'dehydroascorbic': ('脱氢抗坏血酸。维生素 C 交出两个氢之后的氧化型；这一对氧化还原正是它做抗氧化剂和羟化酶辅因子的方式。', ''),
'deprotonated': ('去质子的：失掉 H⁺ 之后带负电。生理 pH 下天冬氨酸和谷氨酸的侧链羧基就是去质子、带负电的。', ''),
'detoxification': ('解毒。卡上指氨的解毒：陆生动物在肝里走尿素循环，把有毒的氨变成尿素排掉。', ''),
'dialysable': ('可透析的：分子小，能透过透析膜。书的经典实验——酵母汁煮过、透析过还留着一个耐热的可透析因子（cozymase，后来证明是 NAD⁺）——这句话本身就证明了辅酶是小分子、不是蛋白质。',
               'Small enough to pass a dialysis membrane, hence not a protein.'),
'diauxie': ('二次生长（双相生长）。大肠杆菌在葡萄糖＋乳糖里先吃完葡萄糖、停一下再换乳糖，长出两段的生长曲线就叫 diauxie，这是分解代谢物阻遏的直接证据。',
            'The two-phase growth curve when glucose is used before lactose.'),
'dihydrouridine': ('二氢尿苷（D）。tRNA 上的稀有碱基之一，尿嘧啶被还原后得到，集中在所谓的 D 环里；同类还有假尿苷和核糖胸苷。', ''),
'dikinase': ('双激酶。一个酶把两个磷酸分别转给两个受体。卡 28 的丙酮酸-磷酸双激酶（pyruvate-phosphate dikinase）把 ATP 用到 AMP ＋ 焦磷酸，等于花掉两个高能键，这是 C4 植物再生 PEP 的代价。', ''),
'dinitrophenyl': ('二硝基苯基（DNP）。Sanger 用 1-氟-2,4-二硝基苯标记肽链游离的 α-氨基，得到黄色的 DNP-氨基酸，水解后就能认出 N 端是谁。', ''),
'dnfb': ('DNFB ＝ 1-氟-2,4-二硝基苯（Sanger 试剂）。温和条件下和肽链的游离 α-氨基反应，给出黄色的二硝基苯基衍生物，用来定 N 端残基。',
         '1-fluoro-2,4-dinitrobenzene, Sanger reagent for N-terminal analysis.'),
'e-oh': ('E-OH ＝ 游离的酶，那个 OH 是活性中心丝氨酸的羟基（胰凝乳蛋白酶的 Ser195）。书写的反应式 E-OH ＋ 硝基苯乙酸酯 → 乙酰化的酶 ＋ 硝基酚，第一步先放出黄色的硝基酚，所以能在分光光度计上看到爆发相。', ''),
'enantiomers': ('对映体：所有不对称碳都相反的一对异构体，互为镜像（如 D-葡萄糖和 L-葡萄糖）。只有一部分不对称碳不同的叫差向异构体（epimer）。',
                'Mirror-image stereoisomers differing at every asymmetric carbon.'),
'endiol': ('烯二醇：双键两端各挂一个羟基（HO–C＝C–OH）。抗坏血酸就是带烯二醇的内酯，所有烯二醇都很强的还原性——维生素 C 的抗氧化能力来自这个基团。', ''),
'endiols': ('烯二醇（复数）。见 endiol：这一类结构都是强还原剂。', ''),
'enediolate': ('烯二醇负离子。Rubisco 把 RuBP 拉成的那个高活性中间体，像碳负离子，活泼到能直接抓住 CO₂——也正因为太活泼，氧气撞上来它也照收，这就是光呼吸的根源。',
               'The carbanion-like RuBP intermediate that attacks CO2 (or O2).'),
'enoyl-coa': ('烯脂酰-CoA。β 氧化第一步脱氢后得到的反式 Δ²-烯脂酰-CoA；第二步由 enoyl-CoA hydratase 加水，它只认反式，也只给 L 型产物。', ''),
'epimerised': ('被差向异构化：只把一个不对称碳的构型翻过来。UDP-葡萄糖在 C-4 上被 UDP-葡萄糖-4-差向异构酶翻成 UDP-半乳糖。', ''),
'epimerises': ('（使）差向异构化：只翻一个不对称碳。半乳糖进糖酵解的最后一步就是 4 位差向异构酶把 UDP-半乳糖翻回 UDP-葡萄糖。', ''),
'foldability': ('可折叠性：一条序列能不能折成稳定结构。卡 land 的说法是，可折叠性本身就是进化适应度曲面上的一个约束——折不起来的序列先被淘汰。', ''),
'folic': ('叶酸的（folic acid ＝ 叶酸，维生素 B₉）。还原成四氢叶酸后搬运一碳单位：羟甲基、甲酰基、亚甲基。', ''),
'galactoside': ('半乳糖苷：半乳糖通过异头碳连出去的化合物。lacY 编码的 galactoside permease 把乳糖运进细胞；X-gal 是人工半乳糖苷，被 β-半乳糖苷酶切开显蓝色；IPTG 也是半乳糖苷，但切不动，所以是「无偿诱导物」。', ''),
'gemcitabine': ('吉西他滨。核苷类抗代谢药（脱氧胞苷类似物），和羟基脲一样打核糖核苷酸还原酶这条路；书里那串抗代谢药的定位是：甲氨蝶呤打 DHFR、5-氟尿嘧啶打胸苷酸合酶。', ''),
'geranyl': ('香叶基（C10）。萜类按五碳砖块累加：异戊烯基焦磷酸 5 碳 → 香叶基 10 碳 → 法尼基 15 碳 → 鲨烯 30 碳 → 四萜 40 碳给出类胡萝卜素。', ''),
'glucosamine': ('氨基葡萄糖：葡萄糖 C-2 上的羟基换成氨基。细胞里通常是 N-乙酰化的（GlcNAc），是几丁质、肽聚糖和糖胺聚糖的砖块。', ''),
'glucuronic': ('葡萄糖醛酸的（glucuronic acid）。葡萄糖末端的 CH₂OH 被氧化成羧基得到的糖醛酸，是透明质酸、硫酸软骨素这些糖胺聚糖的组成单元，肝脏也用它做结合解毒。', ''),
'glutamyl-cysteinyl-glycine': ('γ-谷氨酰-半胱氨酰-甘氨酸，也就是谷胱甘肽（GSH）的全名。注意第一个键是 γ 键（用谷氨酸的侧链羧基），干活的是半胱氨酸那个游离 SH：2 G-SH ⇌ G-S-S-G。', ''),
'homo': ('homo- 前缀：同一种。homoglycan（均一多糖）只由一种单糖组成，heteroglycan 则不止一种。另见 homologue。', ''),
'homologue': ('同系物：结构上只差一个 CH₂ 之类的重复单位。卡 24 用它说 2-氧代戊二酸是丙酮酸的同系物——丙酮酸的甲基上多挂一个 CH₂–COO⁻，所以它的 2-氧代酸那一端反应方式完全一样，也就能被同一类脱氢酶复合体氧化脱羧。', ''),
'hydride': ('氢负离子 H⁻：一个质子带两个电子。NAD⁺ 接的就是它（NAD⁺ ＋ 2H → NADH ＋ H⁺，实际转移的是一个 hydride 加一个游离质子）。卡 31 用「能不能拿住一个 hydride」来区分辅酶和矿物质。',
            'H- : a proton with two electrons, the unit NAD+ accepts.'),
'hydroxy': ('羟基的（–OH）。出现在名字里表示位置，比如 β-羟基-β-甲基戊二酰-CoA（HMG-CoA）、β-羟基羰基化合物。', ''),
'iduronic': ('艾杜糖醛酸（iduronic acid）。葡萄糖醛酸在 C-5 上的差向异构体，是硫酸皮肤素、肝素这类糖胺聚糖里的糖醛酸单元。', ''),
'in-vivo': ('体内的（拉丁语 in vivo）。卡 16 说 DNA 聚合酶 III 的体内功能是真正的复制酶，聚合酶 I 主要是修补和拆引物。', ''),
'isopentenyl': ('异戊烯基（isopentenyl pyrophosphate, IPP）。所有萜类和类固醇的五碳砖块，甲羟戊酸途径的产物。', ''),
'isopeptide': ('异肽键：不是用主链的 α-氨基，而是用侧链的氨基（通常是赖氨酸的 ε-氨基）形成的酰胺键。生物素就是靠异肽键挂在羧化酶的赖氨酸上，泛素连蛋白也是这种键。',
               'An amide bond using a side-chain amino group, not the backbone.'),
'isopropyl': ('异丙基。IPTG ＝ isopropyl β-D-thiogalactoside（异丙基硫代半乳糖苷），能诱导 lac 系统但不会被 β-半乳糖苷酶切掉，所以浓度稳定，属于无偿诱导物。', ''),
'ketokinase': ('β-酮激酶。卡 x-rxn 特别指出：书 p196 图上把那个酶标成 β-ketokinase，这个名字不可能对——激酶是转磷酸基的，那一步做的不是这件事。被问到就照书报，再说明它错在哪。', ''),
'l-serine': ('L-丝氨酸。氨基酸构型的参照点：书把 L-丝氨酸从 L-甘油醛推出来（Fischer 投影里氨基在左边），糖的 D/L 也是从甘油醛来的，所以两套命名同源。', ''),
'linolenic': ('亚麻酸（α-linolenic acid，18:3 n-3）。和亚油酸（18:2 n-6）一起是哺乳动物的两种必需脂肪酸——自己合不出 Δ9 以远的双键，必须从食物里拿。', ''),
'lipoamide': ('硫辛酰胺。硫辛酸通过异肽键挂在酶的赖氨酸上就是这个形态，是丙酮酸脱氢酶复合体的第二个辅酶：又搬酰基又搬电子。卡 31 的关键点是它和辅酶 Q 一样，在书那张表里「对应的维生素」一栏是空的。', ''),
'lipoamide’s': ('硫辛酰胺的（所有格）。见 lipoamide：它在书的辅酶表里没有对应的维生素。', ''),
'lipoate': ('硫辛酸（硫辛酰基）。丙酮酸脱氢酶复合体里搬运酰基和电子的那只手臂，用完之后由 FAD 再由 NAD⁺ 把它重新氧化，复合体才能转下一圈。', ''),
'loci': ('位点（locus 的复数）。卡 taq 指 DNA 分型用的十几个 STR 位点：位点一多，组合就基本上是个人独有的，而且孩子的每一个数值都必须在父母之一那里出现。', ''),
'lysosomal': ('溶酶体的。溶酶体酶走的是和分泌蛋白同一条内质网—高尔基路线，只是在高尔基体上被打了甘露糖-6-磷酸标签才分选出去；这个标签坏了就是 I-cell 病。', ''),
'lysyl': ('赖氨酰的：指赖氨酸残基上的。胶原成熟要三个羟化酶：脯氨酰 4-羟化酶、脯氨酰 3-羟化酶和赖氨酰 5-羟化酶，都要维生素 C。', ''),
'max': ('V max 里的 max ＝ maximum（最大）。最大反应速度，指底物饱和、每一个酶分子都处在复合物状态时的速度。双倒数作图的斜率是 Km/Vmax，截距是 1/Vmax。', ''),
'melatonin': ('褪黑素。松果体（epiphysis）分泌的激素，由色氨酸转变而来——卡 aa 用它做「氨基酸是激素前体」的例子（色氨酸→血清素→褪黑素）。', ''),
'mesophilic': ('嗜温的：最适生长温度在中温区（约 20–45 °C），酶一般 90 °C 就变性。所以用嗜温菌的聚合酶做 PCR，每次变性之后都得重新加酶——这正是 Taq 的意义。', ''),
'methylenetetrahydrofolate': ('N⁵,N¹⁰-亚甲基四氢叶酸。带一碳单位的四氢叶酸形态，胸苷酸合酶就是从它那里拿甲基把 dUMP 甲基化成 dTMP（同时它自己被氧化成二氢叶酸，要 DHFR 还原回来——甲氨蝶呤卡的就是这一步）。', ''),
'microbiogenic': ('微量生物源元素。书 p011 把元素分档：macrobiogenic（H O C N P，>1%）· oligobiogenic（Ca Mg S Na K Fe Cl，0,05–1%）· microbiogenic（Cu Zn Co Mn I Mo）。B₁₂ 里的钴就属于这一档。', ''),
'microflora': ('（共生）菌群。书说纤维素酶主要存在于微生物里、动物几乎没有，所以纤维素作为食物被消化几乎总是靠菌群完成，例子是反刍动物的瘤胃。', ''),
'misincorporated': ('掺错的（核苷酸）。校对活性是 3′→5′ 外切，从正在延伸的那一端往回切，所以它能把刚刚掺错的那一个直接切掉。', ''),
'mobilisable': ('可动员的：需要时能马上取出来用。卡 06 说糖原卷成球、羟基朝向水，所以是可溶、可动员的储备；脂肪则是长期储备。', ''),
'monosodium': ('一钠（盐）。MSG ＝ monosodium glutamate ＝ 谷氨酸钠（味精），谷氨酸的单钠盐；鲜味来自谷氨酸根离子本身。另一处 monosodium urate 是尿酸钠结晶，痛风的病因。', ''),
'msg': ('味精（monosodium glutamate，谷氨酸钠）。谷氨酸的单钠盐，鲜味来自谷氨酸根离子——这是卡 aa 用来说明「谷氨酸在生理 pH 下带负电」的日常例子。', ''),
'multi-subunit': ('多亚基的。SDS 会把多亚基蛋白拆开，所以 SDS 凝胶测到的是单个亚基的分子量，不是整个蛋白的——这是 SDS-PAGE 的一个固定陷阱。', ''),
'mutase': ('变位酶：把一个基团在同一分子内部挪个位置的酶（EC 5 异构酶大类里的一支）。磷酸甘油酸变位酶把磷酸从 C-3 挪到 C-2，需要 2,3-二磷酸甘油酸做启动。', ''),
'mutational': ('突变的。卡上用在 mutational load（突变负荷）一类说法里：低保真的跨损伤合成聚合酶如果不受限制，突变负荷会高到细胞受不了。', ''),
'n-acetylneuraminic': ('N-乙酰神经氨酸，也就是唾液酸（sialic acid）。九碳的酸性糖，挂在糖蛋白、糖脂链的最外端，带负电，是流感病毒等的经典受体。', ''),
'nitrophenyl': ('硝基苯基（酯）。硝基苯乙酸酯是胰凝乳蛋白酶的人工底物，因为切下来的硝基酚是黄色的，反应可以直接在分光光度计上跟踪——爆发相实验靠的就是它。', ''),
'non-heme': ('非血红素（铁）。铁不在卟啉环里，而是由半胱氨酸的硫直接配位，也就是铁硫中心；它靠 Fe²⁺/Fe³⁺ 来回变价传电子。', ''),
'noncovalent': ('非共价的：氢键、离子键、范德华力、疏水作用这一类。书强调膜里脂双层头对头、尾对尾的相互作用「完全是非共价的」——所以膜能流动、能自封。', ''),
'oligosaccharyltransferase': ('寡糖基转移酶（OST）。N-连接糖基化的核心酶：把长在多萜醇（dolichol）上的整块寡糖核心一次性搬到天冬酰胺的侧链酰胺氮上，识别的序列是 Asn-X-Ser/Thr（X 不能是脯氨酸）。大肠杆菌没有这个酶，所以不做 N-糖基化。',
                             'The ER enzyme that transfers the dolichol-linked core glycan onto an asparagine.'),
'oxidisable': ('可被氧化的。卡 28 用它说同一个四碳酸的三种身份：在线粒体里是可氧化的中间体，在糖异生里是旁路，在 C4 里是运碳的载体。', ''),
'oxo': ('氧代（酮基 ＝O）。丙酮酸是三碳的 2-氧代酸（CH₃-CO-COO⁻）——羧基旁边就是酮基，这个排布正是它容易被氧化脱羧的原因。', ''),
'oxo-acid': ('氧代酸（酮酸）。2-氧代酸指酮基紧挨着羧基，如丙酮酸、2-氧代戊二酸；这类分子都能被同一类脱氢酶复合体氧化脱羧。', ''),
'oxoacid': ('氧代酸（酮酸）。β-氧代酸的酮基在 β 位（隔一个碳），特别容易自发脱羧——这是脂肪酸合成、乙酰乙酸这些地方反复用到的化学。', ''),
'two-oxo': ('2-氧代（酸）。酮基在 2 位、紧挨羧基，如丙酮酸、2-氧代戊二酸。书把它们的脱羧归在裂合酶（lyase）反应里。', ''),
'pantoic': ('泛解酸。泛解酸 ＋ β-丙氨酸 ＝ 泛酸（pantothenic acid），泛酸再接上巯基乙胺和 3′,5′-二磷酸腺苷就是辅酶 A。', ''),
'pantothenic': ('泛酸（维生素 B₅，pantothenic acid）。辅酶 A 就建在它上面；干活的是末端那个游离 SH，接上酰基就成了高能硫酯。', ''),
'parametrised': ('被参数化的：用一组数把一个连续空间描述出来。卡 land 说构象空间是连续的，由主链可转动的二面角（每个 α 碳两个单键，肽键本身是平面不能转）来参数化——正因为连续，才谈得上「梯度」和「折叠漏斗」。', ''),
'pentasaccharide': ('五糖。N-连接糖链共有的核心就是一个五糖：三个甘露糖 ＋ 两个 N-乙酰葡糖胺。', ''),
'peptidyl-prolyl': ('肽酰脯氨酰。peptidyl-prolyl cis,trans-isomerase（PPIase）专门催化脯氨酸前面那一个肽键的顺反翻转——天然蛋白里约 6% 的 X-Pro 键是顺式，翻转本身很慢，所以需要酶。', ''),
'phosphoester': ('磷酸酯键：磷酸和一个羟基之间的酯键。蛋白激酶把磷酸挂到丝氨酸、苏氨酸或酪氨酸的羟基上就是磷酸酯；磷脂里头部基团（胆碱、乙醇胺…）也是靠磷酸酯接在磷酸上。', ''),
'phosphogluconolactone': ('6-磷酸葡萄糖酸内酯。磷酸戊糖途径氧化段的第一个产物：6-磷酸葡萄糖在 C-1 被脱氢成内酯，水解成 6-磷酸葡萄糖酸，再氧化脱羧成 5-磷酸核酮糖，一共交出两个 NADPH。', ''),
'phosphoglucose': ('磷酸葡萄糖（异构酶）。phosphoglucose isomerase 把 6-磷酸葡萄糖变成 6-磷酸果糖，是书里 EC 5 异构酶那一类的例子。', ''),
'phosphoribosyl': ('磷酸核糖基。嘧啶环先单独合成为乳清酸，再接到 5-磷酸核糖-1-焦磷酸（PRPP）上；嘌呤则是直接在 PRPP 上一步步搭起来的。', ''),
'phosphosulfate': ('磷酸硫酸（酐）。3′-磷酸腺苷-5′-磷酸硫酸（PAPS）里那个磷酸-硫酸之间的高能键，是细胞里「活化的硫酸根」，硫酸化反应（软骨素硫酸化等）都从它拿硫酸基。', ''),
'photolysing': ('（进行）光解。光系统 II 在类囊体内表面把水光解来填补 P680 的电子空穴：两分子水给出四个质子、四个电子和一个氧——光合放出的氧就是这么来的。', ''),
'photophysics': ('光物理学。卡 27 用它划界：光子怎么在皮秒内变成跨膜的电荷分离，那属于光物理和物理化学，不是生物化学——书也把线画在同一个地方。被追问到这一层可以这样停。', ''),
'photorespire': ('进行光呼吸。Rubisco 把 O₂ 而不是 CO₂ 接到 RuBP 上，走磷酸乙醇酸那条路，白白耗掉 ATP 和还原力并放出 CO₂。热、干、气孔关闭时更严重，C4 和 CAM 就是为了躲它。', ''),
'polyisoprenoid': ('多聚异戊二烯（醇）。dolichol（多萜醇）就是一个多聚异戊二烯醇：书说它有 9–22 个异戊二烯单位，末端是羟基，N-糖基化的寡糖核心就装配在它上面。', ''),
'post-translational': ('翻译后的：肽链合成完（或正在合成）之后对氨基酸残基做的化学修饰——羟化、糖基化、磷酸化、γ-羧化、切前肽等。', ''),
'primosome': ('引发体。后随链上引发酶（primase）不是单干，而是待在这个蛋白复合体里工作，复合体里还带着解旋酶——每段冈崎片段的 RNA 引物就是它做的。', ''),
'prolyl': ('脯氨酰的：指脯氨酸残基上的。胶原要脯氨酰 4-羟化酶和 3-羟化酶（都要维生素 C）；peptidyl-prolyl isomerase 则催化脯氨酸前那个肽键的顺反翻转。', ''),
'proteinogenic': ('成蛋白的：能被遗传密码直接编入蛋白质的那二十种氨基酸（羟脯氨酸这类是翻译后改出来的，不算）。α 螺旋能接纳其中每一种，只有脯氨酸例外。',
                  'The twenty amino acids that are directly encoded and incorporated during translation.'),
'protonating': ('（使）质子化：加上 H⁺。组氨酸侧链 pKa 约 6，把 pH 降到 4–5 就把那个环氮质子化了——镍柱洗脱咪唑标签靠的就是这一点。', ''),
'quantification': ('定量。卡上指免疫检测的定量方式：用已知浓度的抗原做一条标准曲线，样品和标准同批测，从曲线上读浓度。', ''),
'reachable': ('可达到的。动力学那句：竞争性抑制下只要底物加够，最大速度仍然是可以达到的（Vmax 不变，Km 升高）。', ''),
'reclose': ('重新关环。蔗糖和菊粉里果糖的异头碳已经用在糖苷键上，环打不开也关不回去，所以果糖被锁死在呋喃糖形态，也没有还原性。', ''),
'reoxidise': ('重新氧化：把还原态的辅酶变回氧化态，好让它继续干活。丙酮酸脱氢酶复合体里 FAD 再 NAD⁺ 把硫辛酸重新氧化。', ''),
'reoxidised': ('被重新氧化。苹果酸-天冬氨酸穿梭把草酰乙酸还原成苹果酸送进线粒体，在基质里再被重新氧化，交出基质里的 NADH（值 2.5 个 ATP）。', ''),
'reoxidises': ('（把辅酶）重新氧化。呼吸链干的就是这件事：把 NADH 和 FADH₂ 重新氧化，能量的主要部分在这里转换成 ATP。', ''),
'reoxidising': ('重新氧化（动名词）。书说如果不把 NADH 重新氧化，糖酵解会停在 3-磷酸甘油醛那一步——这就是发酵（乳酸、乙醇）存在的唯一理由。', ''),
'reseal': ('重新封闭。电穿孔时电场超过阈值膜上开孔，撤掉电场后几秒内孔自己封回去——正是这个可逆性让这个方法能用。', ''),
'ribityl': ('核糖醇基。核黄素上那条开链的五碳醇侧链。卡 31 的争议点：书正文说活性位点是 N-1 和 N-10，但同一页的结构式把核糖醇挂在 N-10 上，那个氮根本没有自由价——通用写法是 N-1 和 N-5。', ''),
'ribo': ('核糖（型）的，相对于 deoxy-（脱氧）而言。书给的生物合成事实是：脱氧核糖核苷酸由核糖核苷酸还原而来，所以 RNA 的砖块在先、DNA 的在后。', ''),
'selectable': ('可筛选的。selectable marker（筛选标记）让没有质粒的细胞活不下来，细菌里通常就是抗生素抗性基因。', ''),
'semidiscontinuous': ('半不连续（复制）。书自己的词：复制叉上一条新链（前导链）沿着叉的方向连续合成，另一条（后随链）只能倒着做成一段段冈崎片段再连起来——所以整体上一半连续、一半不连续。根源是聚合酶只能 5′→3′ 加核苷酸，而两条模板是反平行的。',
                      'The textbook word (p082) for replication that is continuous on one strand and in fragments on the other.'),
'spectrometry': ('（质谱）法。mass spectrometry 靠质量来分辨，是书列的四种脂肪酸分析法里唯一能定出双键位置的。注意 spectrometry（质谱/分光测定）和 spectroscopy、spectrum 是一家但不同词。', ''),
'sterane': ('甾烷骨架。所有类固醇共有的那套稠合脂环（三个六元环 ＋ 一个五元环），胆固醇、类固醇激素、胆汁酸都长在它上面。', ''),
'stigmasterol': ('豆甾醇。植物的甾醇之一，和麦角甾醇、谷甾醇并列；动物对应的是胆固醇。真菌用麦角甾醇，所以两性霉素这类药才有选择性。', ''),
'subunit': ('亚基：寡聚蛋白里的一条独立多肽链。四级结构讲的就是亚基怎么拼；SDS 凝胶测的是单个亚基的分子量。', ''),
'supersecondary': ('超二级结构：介于二级和三级之间的固定组合，例如 βαβ 模体、螺旋-转角-螺旋、β 桶。书说这一层和结构域是后来才补进四层划分里的。', ''),
'thiolytic': ('硫解的。β 氧化第四步：CoA-SH 的巯基进攻 β-酮脂酰-CoA，把链切下两个碳，放出乙酰-CoA，剩下的脂酰-CoA 短了两碳再转一圈。', ''),
'thymidylate': ('胸苷酸（dTMP）。thymidylate synthase（胸苷酸合酶）把 dUMP 甲基化成 dTMP，甲基来自 N⁵,N¹⁰-亚甲基四氢叶酸——5-氟尿嘧啶打的就是这个酶。', ''),
'tollens': ('Tollens 试剂（银氨溶液）。和 Fehling 试剂一样用来验还原糖：糖的游离异头碳把银离子还原成单质银（银镜），Fehling 里还原的则是铜。', ''),
'trans-isomerases': ('（cis,trans-）异构酶。卡上出现的是 peptidyl-prolyl cis,trans-isomerases：专门催化脯氨酸前那一个肽键顺反翻转的酶家族。', ''),
'trisphosphate': ('三磷酸。卡 32 指肌醇三磷酸（IP₃）：它打开钙通道放出 Ca²⁺，同时产生的二酰甘油（DAG）激活蛋白激酶 C——这是磷脂酰肌醇信号通路的两个第二信使。', ''),
'tyrosinase': ('酪氨酸酶。含铜的氧化酶，把酪氨酸氧化成多巴再往下做黑色素；卡 31 用它做「铜是酶的辅因子」的例子（锌在醇脱氢酶、铁在细胞色素、铜在酪氨酸酶）。', ''),
'udp-glcnac': ('UDP-N-乙酰葡糖胺。活化形式的 N-乙酰葡糖胺：单糖挂在核苷二磷酸上才有足够的能量被转移。N-糖基化的核心就用 UDP-葡萄糖、UDP-GlcNAc、GDP-甘露糖这几种核苷糖来搭。', ''),
'uggt': ('UGGT ＝ UDP-葡萄糖:糖蛋白葡萄糖基转移酶。内质网里的折叠检查员：如果糖蛋白还没折好，它就把那一个葡萄糖再加回去，于是重新被 calnexin/calreticulin 抓住，再折一轮。',
         'UDP-glucose:glycoprotein glucosyltransferase, the folding sensor of the calnexin cycle.'),
'unbranched': ('不分支的（直链的）。纤维素是不分支的 β-1,4 葡聚糖；直链淀粉（amylose）是不分支的 α-1,4 链，卷成螺旋，遇碘变蓝。', ''),
'unrelated': ('不相干的、彼此无关的。卡 14 那句的意思是：那四件事不是四个互不相干的东西，它们背后是同一个道理。', ''),
'unsorted': ('未被分选的。指蛋白质还没被分拣到该去的地方——内质网—高尔基这条路上，溶酶体酶靠甘露糖-6-磷酸标签被分选出去，没有标签就分不出去（I-cell 病）。', ''),
'untemplated': ('无模板添加的。Taq 会在产物 3′ 端多加一个模板上并不存在的腺苷酸——TA 克隆就是利用这个多出来的 A。', ''),
'uridylyltransferase': ('尿苷酰转移酶。半乳糖代谢的第二步：hexose-1-phosphate uridylyltransferase 把 UDP 从 UDP-葡萄糖换到半乳糖-1-磷酸上，得到 UDP-半乳糖（这个酶缺了就是半乳糖血症）。', ''),
'valency': ('化合价（变价）。卡 31 用它分矿物质的两种角色：一种坐在活性中心里靠变价传电子（Fe²⁺/Fe³⁺、Cu⁺/Cu²⁺），另一种只是在体液里带电荷做电解质。', ''),
'b-type': ('b 型细胞色素。细胞色素按血红素的种类分 a、b、c 三型；b 型的血红素是非共价结合的原卟酕 IX，铁被四个氮抱在卤素环中心，靠 Fe²⁺/Fe³⁺ 变价传电子。复合物 III 里就带两个 b 型细胞色素，加上细胞色素 c₁ 和一个铁硫蛋白。', ''),
'co-translational': ('共翻译的：一边翻译一边就已经在发生。分泌蛋白的信号肽一出核糖体就被 SRP 认出、整个核糖体被拉到内质网膜上，剩下的肽链是一边合成一边穿过去的；信号肽也是在链还没做完时就被切掉的。对比 post-translational（翻译后）。', ''),
'co-translationally': ('共翻译地：在肽链还在合成的同时就完成。见 co-translational——这是内质网转运和线粒体转运（翻译后）的关键区别。', ''),
'codogenic': ('编码链——但注意，指的是真正被读的那一条，也就是模板链（template / antisense strand），因为它“带着密码”。这是这本书自己的用词（codogenic strand），英语教材里常用 template strand；另一条叫 coding / sense strand，序列和 mRNA 一样（T 换 U）。答题时先说它是哪一条，再说这是书的叫法。', 'The book word for the strand that is actually read as template.'),
'eikosanoids': ('二十碳类（eicosanoids，书里拼成 eikosanoids）。含二十个碳原子（希腊语 eikosi 就是二十），全部来自花生四烯酸 20:4：前列腺素、前列环素、血栓烷、白三烯。它们是激素四大类里的一类，也是脂类“信号”那条功能的落点。', ''),
'nter': ('这是 Günter 被 ü 切开后剩下的后半截，不是一个词。Günter Blobel：提出信号肽假说的人，1975 年与 Bernhard Dobberstein 做出关键实验，1999 年诺贝尔奖。', ''),
'beta-ketokinase': ('β-酮激酶。书 p196 的图把那一步的酶标成这个名字，而这个名字不可能对——激酶干的是转磷酸基，那一步做的不是这件事。照书报，被追问再说它错在哪里。', ''),
'gastrin': ('胃泌素。胃穦部 G 细胞分泌的肽类激素，促进胃酸分泌和胃黏膜生长。卡上拿它做例子是因为它的酪氨酸侧链被硫酸化（翻译后修饰的一种）。', ''),
'macromolecular': ('大分子的。指分子量很大的物质（蛋白质、多糖、核酸，书里还把木质素 lignin 也算在内）。', ''),
'vectorial': ('矢量的、有方向的。呼吸链的关键性质：质子不是随便放，而是被定向地从膜的一侧泵到另一侧（传递体交替搬“氢原子”和“只搬电子”造成的）。正是这个方向性把化学能变成跨膜梯度，再变成 ATP。', ''),

# ---------------- 2 · 人名、菌名、品牌 ----------------

'blobel': ('Günter Blobel（布洛贝尔），提出信号肽假说的人：蛋白质自己带着一段「地址」，决定去哪里。1975 年和 Bernhard Dobberstein 用无细胞体系做出关键实验，1999 年拿诺贝尔生理学或医学奖。考官问「这是谁做的」时就答他。',
            'Gunter Blobel, signal hypothesis; Nobel Prize 1999.'),
'blobel’s': ('Blobel 的（所有格）。Günter Blobel，信号肽假说的提出者，1999 年诺贝尔奖。', ''),
'dobberstein': ('Bernhard Dobberstein（多伯斯坦）。1975 年和 Günter Blobel 一起，在无细胞体系里翻译分泌蛋白的 mRNA，做出了支持信号肽假说的实验——问「谁做的」时两个名字一起报。', ''),
'buchner': ('Eduard Buchner（布赫纳）。1897 年证明发酵是化学过程：用无细胞的酵母汁也能发酵，不需要活细胞，从此「活力论」被推翻。搭配记忆：Ostwald 1893 年证明酶是催化剂。',
            'Eduard Buchner, 1897: fermentation runs in cell-free yeast extract.'),
'chargaff’s': ('Chargaff 规则（查伽夫法则）。Erwin Chargaff 发现任何 DNA 里腺嘌呤＝胸腺嘧啶、鸟嘌呤＝胞嘧啶，这是 Watson-Crick 双螺旋模型的直接依据之一。', ''),
'watson': ('James Watson（沃森）。1953 年和 Francis Crick 用模型搭建的方法提出 DNA 双螺旋；依据是 Chargaff 的碱基比例和 Franklin、Wilkins 的 X 射线衍射图。', ''),
'meselson': ('Matthew Meselson（梅塞尔森）。和 Frank Stahl 1958 年用 ¹⁵N 密度梯度离心证明 DNA 是半保留复制。⚠ 捷克书里没有这个实验，说的时候要带 generally。',
             'Meselson and Stahl, 1958: semiconservative replication.'),
'reiji': ('Reiji Okazaki（冈崎令治）。1960 年代末用脉冲标记大肠杆菌，发现新合成的 DNA 里有一批短片段——就是后来以他命名的冈崎片段，后随链不连续合成的证据。', ''),
'lineweaver': ('Hans Lineweaver（莱恩威弗）。和 Dean Burk 一起提出双倒数作图（1/v 对 1/[S]），把米氏双曲线拉成直线，斜率 Km/Vmax、纵截距 1/Vmax。', ''),
'lineweaver-burk': ('Lineweaver-Burk 双倒数作图：1/v 对 1/[S] 画成直线。用它是因为在高底物浓度下直接测速度既不准又费底物，而外推到直线上就能读出 Vmax 和 Km；抑制类型也是看直线怎么变（竞争性 Vmax 不变、Km 升高）。',
                    'The double-reciprocal plot of 1/v against 1/[S].'),
'menten': ('Maud Menten（门坦）。加拿大生化学家，和 Leonor Michaelis 一起给出米氏方程（Michaelis-Menten equation）；别念成两个人的姓合成的一个词——是两个人。', ''),
'pardee': ('Arthur Pardee（帕迪）。1959 年 PaJaMa 实验（Pardee-Jacob-Monod）的第一作者：用细菌接合把 lac 基因送进受体细胞，看酶什么时候开始合成，从而证明存在一个可扩散的阻遏物。⚠ 书里没有，要说带 generally。', ''),
'ller-hill': ('这是 Müller-Hill 被 ü 切碎后剩下的后半截。Benno Müller-Hill 和 Walter Gilbert 在 1960 年代分离出 lac 阻遏蛋白，后来解出它跟操纵基因 DNA、跟诱导物结合的结构。', ''),
'sewall': ('Sewall Wright（休厄尔·赖特）。群体遗传学家，1932 年提出「适应度地形（adaptive landscape）」这个图景——卡 land 借它来讲折叠漏斗和构象空间。⚠ 来自群体遗传学而不是生化，报的时候带 generally。', ''),
'thermus': ('Thermus（栖热菌属）。嗜热细菌，Taq 聚合酶来自其中的 Thermus aquaticus——1960 年代在黄石公园温泉里分离到的那种菌，它的酶能扛住 95 °C 的变性步骤，PCR 才不用每轮重新加酶。⚠ 捷克书里 Taq 和 Thermus aquaticus 一次都没出现。',
            'Thermus aquaticus, the hot-spring bacterium that Taq polymerase comes from.'),
'aquaticus': ('（Thermus）aquaticus，拉丁语「水生的」，是那株温泉细菌的种名。Taq 这个名字就是 Thermus aquaticus 的缩写。', ''),
'subtilis': ('（Bacillus）subtilis，枯草芽孢杆菌的种名。革兰阳性模式菌，和肺炎链球菌一样是天然感受态的经典例子：它自己带着一套把 DNA 吸到表面、抽一条链进去的机器，而且感受态受调控、只在特定条件下打开。', ''),
'pneumoniae': ('（Streptococcus）pneumoniae，肺炎链球菌的种名。天然感受态的经典例子，也是 Griffith 转化实验和 Avery 证明「遗传物质是 DNA」用的那种菌。', ''),
'kapa': ('KAPA（卡帕），PCR 酶的商品名，KAPA HiFi 是常用的高保真聚合酶（KAPA Biosystems，现属 Roche）。它带 3′→5′ 校对活性，要克隆、要测序的产物用它；只是查有没有条带就用 Taq。',
         'KAPA HiFi: a commercial high-fidelity, proofreading PCR polymerase.'),
'kelvin': ('开尔文（K），热力学温标。0 K 是绝对零度，298 K ＝ 25 °C。所有热力学式子里的 T 都要用 K：ΔG°′ ＝ −RT ln K′eq，25 °C 下结合力每强十倍大约对应 5,7 kJ/mol。', ''),
'svedberg': ('Svedberg（斯韦德贝里）。① 沉降系数的单位 S，1 S ＝ 10⁻¹³ 秒，核糖体 70S、50S、30S 用的就是它（所以 50 ＋ 30 ≠ 70，S 不可加）。② Svedberg 方程：Mr ＝ R·T·s / [D·(1 − v̄·ρ)]，因为沉降系数和分子量不成正比，要算分子量还得带上扩散系数和偏比容。③ 词源是瑞典化学家 The Svedberg，超速离心机的发明人。',
              'The sedimentation unit S (1e-13 s) and the equation relating s to Mr.'),

# ---------------- 3 · 符号、缩写、片段 ----------------

'mg': ('镁（Mg²⁺）。酶最常见的金属辅因子：ATP 在细胞里实际上是以 Mg-ATP 复合物存在的，激酶、聚合酶用的都是它；书里磷酸酶的激活剂也是镁。', ''),
'mg-atp': ('Mg-ATP 复合物。ATP 的磷酸基带负电，Mg²⁺ 中和一部分电荷、把构象摆正，激酶和聚合酶真正的底物是 Mg-ATP 而不是裸的 ATP。⚠ 书 p043 给己糖激酶印的是 Mn²⁺，通用写法是 Mg-ATP——照书报，被追问再说明差别。', ''),
'zn': ('锌（Zn²⁺）。不变价的结构性/催化性金属：羧肽酶、醇脱氢酶、碳酸酐酶里都有它，锌指结构域也靠它把折叠钉住。', ''),
'mn': ('锰（Mn²⁺）。金属辅因子之一。⚠ 书 p043 把己糖激酶的金属印成 Mn²⁺（通用写法是 Mg-ATP）；光系统 II 放氧的锰簇也是它。', ''),
'ni': ('镍（Ni²⁺）。她实验室的用法：固定在柱子上的 Ni²⁺ 接受组氨酸咪唑环上未质子化氮给出的孤对电子，形成配位键——这就是 His-tag 亲和纯化，用咪唑或降 pH 竞争洗脱。', ''),
'ca': ('钙（Ca²⁺）。① 转化实验里 CaCl₂ 屏蔽 DNA 磷酸骨架和细菌表面之间的负电排斥，冰上处理后一次短促热激把 DNA 送进去。② 信号里 Ca²⁺ 是第二信使，IP₃ 打开钙通道。③ γ-羧基谷氨酸螯合的也是它。', ''),
'ec': ('EC 号 ＝ 酶学委员会（Enzyme Commission）编号，写成四位数如 EC 2.6.1.1。第一位是六大类（1 氧化还原酶、2 转移酶、3 水解酶、4 裂合酶、5 异构酶、6 连接酶），后三位要查表。每个酶都有系统名、常用名和一个 EC 号。⚠ 全书只印出过九个 EC 号。',
       'Enzyme Commission number: class.subclass.sub-subclass.serial.'),
'sam': ('SAM ＝ S-腺苷甲硫氨酸（S-adenosylmethionine）。细胞里的通用甲基供体，甲基转移反应（DNA 甲基化、肾上腺素合成等）几乎都从它拿甲基；书把它列在辅酶表之外的补充里。', ''),
'bcaa': ('BCAA ＝ 支链氨基酸（branched-chain amino acids）：缬氨酸、亮氨酸、异亮氨酸这三个。这是健身补剂的营销名字，生化上它们的共同点是侧链带分支、都由同一个支链 α-酮酸脱氢酶复合体降解。', ''),
'hsp': ('HSP ＝ 热激蛋白（heat-shock protein）。分子伴侣，名字来自它们在热应激时大量诱导。书点名的是 GroEL/GroES 和 hsp70。要点：伴侣只是催化折叠、把错误折叠的再拆开重来，它不提供信息——信息在序列里。', ''),
's-s': ('S-S ＝ 二硫键（–S–S–）。两个半胱氨酸的巯基被氧化连在一起，得到胱氨酸（cystine）。它是唯一常见的共价侧链交联，把折叠锁住；碱能断、还原剂断成两个半胱氨酸、过甲酸则不可逆地氧化成半胱磺酸。',
        'A disulfide bridge: two cysteine thiols oxidised together.'),
'co-nh': ('CO-NH 就是肽键写开的样子：前一个氨基酸的羰基（C＝O）连着后一个的氮（N–H）。电子在 O-C-N 上离域，所以 C–N 带部分双键性质、不能自由转动，整个肽单元是一个平面。书上把它叫 peptide (amide) bond，也就是「肽键（酰胺键）」。',
          'The peptide (amide) bond written out: C=O of one residue joined to N-H of the next.'),
'conh': ('–CONH₂ ＝ 酰胺基。天冬酰胺和谷氨酰胺的侧链末端就是它：羧基换成酰胺，所以不带电。天冬酰胺侧链的这个氮正是 N-连接糖基化唯一的挂点。', ''),
'n-h': ('N-H 键。氢键的给体之一（O-H 和 N-H 都是永久偶极）。α 螺旋和 β 折叠靠的就是主链自己的 C＝O 和 N-H 之间的氢键。', ''),
'o-h': ('O-H 键。永久偶极，氢键的给体；接受氢键的是另一端的孤对电子。水、羟基、糖的稳定性都从这里来。', ''),
'o-c-n': ('O-C-N 指肽键上离域的那三个原子：电子共享在羰基氧—碳—氮之间，而不是老实待在氮上。后果是 C–N 键长介于单双键之间、不能自由转动，肽单元成为刚性平面（书 Obr. 2.6）。', ''),
'o-beta': ('出现在糖苷命名里，如 4-O-β-D-吡喃葡萄糖基：O 指连接两个糖的那个氧，β 是异头碳的构型。麦芽糖是 4-O-α，纤维二糖是同一个结构的 4-O-β 异构体——一个 α 一个 β，消化得了和消化不了的区别就在这儿。', ''),
'h-plus': ('H⁺，质子（氢离子）。书把反应写成 NAD⁺ ＋ 2H → NADH ＋ H⁺：两个氢里只有一个（以 hydride 形式）上了辅酶，另一个以自由质子留在溶液里。', ''),
'nad': ('NAD⁺ ＝ 烟酰胺腺嘌呤二核苷酸，来自维生素 B₃（烟酸），接受一个 hydride 变成 NADH，是分解代谢的主力电子载体。（NADPH 则专管合成代谢。）大肠杆菌的 DNA 连接酶用 NAD⁺ 而不是 ATP 做能量来源，这是书特意点的对比。', ''),
'nadp-plus': ('NADP⁺。比 NAD⁺ 多一个 2′-磷酸，细胞用这个磷酸把两套电子池分开：NAD⁺/NADH 管分解代谢和呼吸链，NADP⁺/NADPH 管还原性合成（脂肪酸合成、磷酸戊糖途径、光合暗反应）。光合作用里 NADP⁺ 在 −320 mV，水在 +820 mV。', ''),
'nf': ('公式 ΔG°′ ＝ −nFΔE°′ 里的 nF：n 是转移的电子数，F 是法拉第常数（96 485 C/mol）。这条式子把氧化还原电位差换算成自由能——呼吸链 −0,32 V → +0,82 V 的落差算出来就是能推动 ATP 合成的那个数量级。', ''),
'ei': ('EI ＝ 酶-抑制剂复合物。Ki 的定义就是它的解离常数：[E][I]/[EI]。非竞争性抑制里 Ki ＝ Ki′，表示抑制剂结合游离酶（EI）和结合酶-底物复合物（EAI）一样容易。', ''),
'es': ('ES ＝ 酶-底物复合物（书里也写 EA）。米氏机制的第一步 E ＋ S ⇌ ES → E ＋ P；诱导契合的完整逻辑是：酶最贴合的不是底物而是过渡态，所以从 ES 到产物的能垒被降低了。', ''),
'eab': ('EAB ＝ 同时结合了两个底物的酶（双底物动力学里的三元复合物）。相对的，EAI 是酶-底物-抑制剂；反竞争性抑制的特点就是抑制剂只结合这种已经带着底物的复合物。', ''),
'a-zero': ('A₀（A-zero）。光系统 I 里紧接着 P700 的第一个电子受体，是一个叶绿素 a 分子。电子的路线：P700* → A₀ → A₁（叶醌）→ 三个铁硫中心 → 铁氧还蛋白 → 铁氧还蛋白-NADP⁺ 还原酶（FAD 黄素蛋白）在基质侧做出 NADPH。', ''),
'f-zero': ('F₀（F-zero）。ATP 合酶埋在膜里的那部分，质子从这里穿过并使它旋转（下标是字母 o，因为最早是「对寡霉素敏感」的部分）。', ''),
'f-one': ('F₁（F-one）。ATP 合酶伸在基质一侧的头部，真正合成 ATP 的催化亚基就在这里（α₃β₃γδε）。F₀ 转、F₁ 催化。', ''),
'cf': ('CF ＝ 叶绿体的 ATP 合酶（CF₀/CF₁），C 就是 chloroplast。书特意把它和线粒体的 F₀/F₁ 并排画，说明两者是同一台机器。', ''),
'cf-zero': ('CF₀。叶绿体 ATP 合酶埋在类囊体膜里的那部分，对应线粒体的 F₀。', ''),
'cf-one': ('CF₁。叶绿体 ATP 合酶伸向基质（stroma）一侧的头部，对应线粒体的 F₁——注意方向：类囊体腔里质子多，头朝基质，所以 ATP 做在基质里。', ''),
'p-star': ('P*（P-star）＝ 被激发的反应中心色素。书的原话是：只有 P ＋ 光子 → P* 这一步严格依赖光，后面的电子传递都不需要光。P680、P700 的数字是它们的吸收峰波长。', ''),
'b-one': ('维生素 B₁ ＝ 硫胺素（thiamine）。它的辅酶形式是硫胺素焦磷酸（TPP），负责 2-氧代酸的脱羧（丙酮酸脱氢酶、转酮醇酶）。缺了就是脚气病。', ''),
'b-two': ('维生素 B₂ ＝ 核黄素（riboflavin）。黄素辅酶 FMN 和 FAD 都建在它上面：FMN 是核黄素-5′-磷酸，FAD 是 FMN 再通过焦磷酸键接上 AMP。', ''),
'b-six': ('维生素 B₆ ＝ 吡哆醇（pyridoxine）。细胞把它变成磷酸吡哆醛（PLP），这是所有转氨酶的辅酶（EC 2.6.1 那一类），也管脱羧和消旋。', ''),
'k-two': ('维生素 K₂（甲萘醌类）。管 γ-羧化（凝血因子的 γ-羧基谷氨酸）。书还指出：维生素 K₂、维生素 E 和辅酶 Q 的疏水侧链在生物合成上都来自植醇（phytol），和叶绿素的尾巴同源。', ''),
'n-one': ('N-1，指黄素（核黄素/FMN/FAD）异咯嗪环上的 1 号氮。⚠ 书正文说活性位点是 N-1 和 N-10，但同一页的结构式把核糖醇挂在 N-10 上，那个氮没有自由价；通用说法是 N-1 和 N-5。用书的一半打书的另一半，比引外部教材稳。', ''),
'n-five': ('N-5，黄素异咯嗪环上的 5 号氮，和 N-1 一起接受两个氢变成 FADH₂/FMNH₂——这是通用且正确的写法（书正文写的是 N-1 和 N-10）。', ''),
'n-ten': ('N-10，黄素环上接核糖醇侧链的那个氮。正因为侧链占着它，它没有自由价，不可能参与加氢——这是书正文自相矛盾的地方。', ''),
'n-six': ('n-6（旧写法 ω-6）。不饱和脂肪酸的编号方式之一：从甲基那一端往回数，第一个双键在第 6 个碳。这个数定义「系列」，因为哺乳动物改不了甲基端的双键位置——亚油酸 18:2 n-6 和 α-亚麻酸 18:3 n-3 因此是必需脂肪酸。', ''),
'g-c': ('G-C 碱基对（鸟嘌呤-胞嘧啶），三个氢键；A-T 只有两个（书 p073）。所以 GC 含量高的 DNA 熔点更高，这也是设计引物退火温度时要看 GC 含量的原因。', ''),
't-loop': ('T 环（TψC 环）。tRNA 三叶草结构上的一个环，名字来自里面的核糖胸苷（ribothymidine，即 T）和假尿苷；tRNA 的稀有碱基主要就集中在 D 环和 T 环里。', ''),
'x-pro': ('X-Pro 键：任意残基后面接脯氨酸的那个肽键。天然蛋白里大约 6% 的 X-Pro 键是顺式（其他肽键几乎全是反式），因为脯氨酸的环让顺反两式能量接近；翻转很慢，所以细胞派了 peptidyl-prolyl cis,trans-isomerase 去催化。', ''),
'asn-x-ser': ('Asn-X-Ser/Thr，N-连接糖基化的识别序列（sequon）：天冬酰胺，任意一个残基（不能是脯氨酸），然后丝氨酸或苏氨酸。寡糖基转移酶就认这三个位置，糖挂在天冬酰胺的侧链酰胺氮上。', ''),
'val': ('Val ＝ 缬氨酸（valine）的三字母缩写，单字母 V。支链、非极性、必需氨基酸，属于 BCAA 三个之一。', ''),
'val-asp': ('Val-Asp…，卡 08 里那段 Val-Asp₄-Lys 六肽：肠肽酶（enteropeptidase）从胰蛋白酶原 N 端切掉的就是它，切完胰蛋白酶就活了，再去激活胰凝乳蛋白酶原等其他酶原。', ''),
'trpe': ('trpE，色氨酸操纵子的第一个结构基因。大肠杆菌的 trp 操纵子有五个结构基因 trpE、D、C、B、A，从分支酸（chorismate）做出三个酶；trpE 和 trpD 的产物合成邻氨基苯甲酸合酶。', ''),
'trpd': ('trpD，色氨酸操纵子第二个基因。它和 trpE 的产物一起组成邻氨基苯甲酸合酶（anthranilate synthase）。', ''),
'trpc': ('trpC，色氨酸操纵子第三个基因。它的产物连着催化两步反应——五个基因只做出三个酶，就是因为 trpC 一个顶两步。', ''),
'trpb': ('trpB，色氨酸操纵子的基因之一。trpB 和 trpA 的产物组成色氨酸合酶（α₂β₂），把吲哚-3-甘油磷酸和丝氨酸拼成色氨酸，同时放出 3-磷酸甘油醛。', ''),
'trpa': ('trpA，色氨酸操纵子最后一个基因。和 trpB 一起组成色氨酸合酶 α₂β₂。五个基因 E→A、三个酶，这是这题的记忆骨架。', ''),
'trpl': ('trpL ＝ 前导序列（leader）。启动子和 trpE 之间那段 162 个核苷酸的先导区，末端带一个衰减子（attenuator）；先导肽里有两个连着的色氨酸密码子——色氨酸够不够，决定核糖体走到哪里、决定 mRNA 折成终止还是抗终止的发夹。', ''),
'ompa': ('OmpA ＝ 大肠杆菌外膜蛋白 A。它的信号肽是常用的周质分泌信号：想让重组蛋白进周质（那里能形成二硫键、纯化也干净），就在前面接 pelB 或 OmpA 信号。', ''),
'pelb': ('pelB 信号肽，来自欧文氏菌的果胶酸裂解酶 B。和 OmpA 信号一样，接在重组蛋白 N 端把它送进大肠杆菌的周质腔——周质是氧化环境，二硫键能正确形成。', ''),
'pgk': ('PGK ＝ 磷酸甘油酸激酶（phosphoglycerate kinase）。糖酵解里第一个产 ATP 的酶（1,3-二磷酸甘油酸 → 3-磷酸甘油酸）。在光合暗反应里这一步倒着走：3-磷酸甘油酸先花 1 个 ATP、再花 1 个 NADPH 变成 3-磷酸甘油醛。', ''),
'glc': ('Glc ＝ 葡萄糖（glucose）的标准缩写。常见组合：UDP-Glc（UDP-葡萄糖，糖原合成的活化形式）、GlcNAc（N-乙酰葡糖胺）、GlcA（葡萄糖醛酸）。', ''),
'glcn': ('GlcN ＝ 氨基葡萄糖（glucosamine）的缩写；加乙酰基就是 GlcNAc（N-乙酰葡糖胺），肝素里还有 N-磺基的形式（N-sulfo-glucosamine）。', ''),
'cdp': ('CDP ＝ 胞苷二磷酸。核苷二磷酸是糖和脂的「活化」形式：磷脂合成走 CDP-二酰甘油或 CDP-胆碱这条路（书 p052 把 UDP、CDP 放在一起讲）。', ''),
'cmp': ('CMP ＝ 胞苷一磷酸。唾液酸（N-乙酰神经氨酸）的活化形式是 CMP-唾液酸——别的糖用 UDP 或 GDP，唯独唾液酸用单磷酸，这是个爱被追问的细节。', ''),
'co': ('卡上的 co 绝大多数是 CO₂（二氧化碳）的下标被吃掉后剩下的「CO」——看上下文是碳固定、脱羧还是呼吸链。单独的 CO 才是一氧化碳（结合血红素、毒性）。', ''),
'nt': ('nt ＝ nucleotide(s)，核苷酸数，用来说单链的长度（双链用 bp）。例如 trp 的先导序列长 162 nt，全酶做出 ≤9 nt 的短转录物后 σ 因子才离开。', ''),
'nm': ('nm ＝ 纳米（10⁻⁹ m），说光的波长。常考的几个：蛋白在 280 nm 有吸收（色氨酸、酪氨酸），核酸在 260 nm；叶绿素吸收在 415–440 和 640–700 nm；质体蓝素约 597 nm。', ''),
'si': ('SI ＝ 国际单位制。书 p058 说酶活性的 SI 单位是 katal：每秒转化 1 mol 底物所需的酶量。实验室常用的 U（每分钟 1 μmol）不是 SI 单位。', ''),
'hm': ('乳酸脱氢酶同工酶的写法。LDH 是四聚体，由 H（心肌型）和 M（肌肉型）两种亚基拼成五种组合：H₄、H₃M、H₂M₂、HM₃、M₄。HM₃ 就是一个 H 加三个 M。它们动力学性质不同，组织分布不同，所以临床上能用同工酶谱判断是哪个器官受损。', ''),
'ru': ('Ru 是核酮糖（ribulose）的缩写前缀：Ru5P ＝ 5-磷酸核酮糖，RuBP ＝ 1,5-二磷酸核酮糖（Rubisco 的底物）。卡尔文循环的再生段就是把三碳糖重排回 Ru5P，再花一个 ATP 磷酸化成 RuBP。', ''),
'de': ('卡上有两处：① BL21(DE3) 里的 DE3，是整合进大肠杆菌基因组、带 T7 RNA 聚合酶基因的那个 λ 溶原，聚合酶由 lacUV5 启动子驱动，所以加 IPTG 才开工。② de-excitation（去激发）里被连字符切下来的前缀，指激发态回到基态的那些途径（荧光、发热、或者被光合反应中心用掉）。', ''),
'i’s': ('这是 polymerase I 的所有格（「聚合酶 I 的」）。书特别点出：聚合酶 I 的 5′→3′ 活性和别的核酸酶不是一类——它从缺口开始在双链内部切，一次能切掉多达十个核苷酸，正是靠这个把后随链的 RNA 引物拆掉并同时补上 DNA。', ''),
'u’s': ('「U」的复数，指一串尿苷。不依赖 rho 的终止子长这样：G+C 富集的回文转录成自我互补的 RNA 折出稳定发夹，后面紧跟四到十个 A-T 对，在 RNA 上读出来就是一串 U——发夹加上 rU:dA 这种弱配对，转录就掉下来了。', ''),
}
