"""Generate the node index the 速通简洁版 needs, from the real app's data.

    python tools/build-lite-index.py

WHY AN INDEX AND NOT A COPY
The obvious way to build a second app is to copy biochemie_pro. That would fork 9 MB
of prose across 78 files — and in one afternoon that prose needed five separate
repairs (capitals, base pairs, bold that ran into brackets, a duplicated panel, a
note filed under an empty key). Every one of those would have had to be found and
fixed twice, and the two copies would drift apart silently.

So the lite app does not own the prose. It owns the SPINE (data/spine_*.js, written
by hand, one chain per node) and reads everything else — which nodes exist, what
they are called, what chapter they sit in — from this generated index. Regenerate it
whenever biochemie_pro's node list changes; never edit it by hand.

The index carries titles and structure only, about 100 KB, so the lite app loads in
a fraction of the time on a tablet. The full prose stays one click away in the other
app, which is the whole point: this one is the thread, that one is the detail.
"""
import json, pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOPICS = ROOT / "tools" / "topics.json"
LITE = ROOT / "biochemie_lite"
OUT = LITE / "data" / "nodes.js"

if not TOPICS.exists():
    sys.exit("run tools/dump-topics.py first")

topics = json.loads(TOPICS.read_text(encoding="utf-8"))

def keep(t):
    return {
        "id": t["id"],
        "book": t.get("book") or "cz",
        "kind": t.get("kind") or "section",
        "chapter": t.get("chapter"),
        "section": t.get("section"),
        "enTitle": t.get("enTitle"),
        "cnTitle": t.get("cnTitle"),
        "topicKey": t.get("topicKey"),
        # how much detail waits in the full app, so the lite app can say so
        "detail": sum(len(p.get("en") or "") for p in t.get("points") or []),
        "nPoints": len(t.get("points") or []),
        "nTerms": len(t.get("terms") or []),
    }

def sync_spine_tags():
    """Rewrite index.html's spine <script> block from the files that exist.

    They were hardcoded, so a spine written into a new data/spine_*.js file simply
    did not load and the work was invisible — the sidebar would still say the section
    had no thread. Keeping the page static (no fetch, no dynamic injection) matters:
    it has to open from a file on an iPad with no server.
    """
    idx = LITE / "index.html"
    if not idx.exists():
        return
    files = sorted(p.name for p in (LITE / "data").glob("spine_*.js"))
    block = ("<!-- The spine: one hand-written chain per node, a chapter at a time.\n"
             "     GENERATED by tools/build-lite-index.py — add a spine_*.js file and\n"
             "     re-run; do not hand-edit this list. -->\n"
             + "\n".join(f'<script src="data/{f}"></script>' for f in files))
    html = idx.read_text(encoding="utf-8")
    pat = re.compile(r"<!-- The spine:.*?-->\s*(?:<script src=\"data/spine_[^\"]+\"></script>\s*)*",
                     re.S)
    if not pat.search(html):
        sys.exit("could not find the spine <script> block in index.html")
    idx.write_text(pat.sub(block + "\n", html, count=1), encoding="utf-8")
    print(f"index.html: {len(files)} spine file(s) linked — {', '.join(files)}")

nodes = [keep(t) for t in topics]
OUT.parent.mkdir(parents=True, exist_ok=True)
header = (
    "/* Node index for the 速通简洁版. GENERATED by tools/build-lite-index.py from\n"
    "   biochemie_pro's own data — do not edit by hand.\n\n"
    "   Titles and structure only. The lite app deliberately does not copy the prose:\n"
    "   forking 9 MB of text across 78 files would mean finding and fixing every\n"
    "   defect twice, and the two copies drifting apart without anyone noticing.\n"
    "   The spine lives in data/spine_*.js; the detail stays in the other app. */\n"
    "window.BIOLITE_NODES = ")
OUT.write_text(header + json.dumps(nodes, ensure_ascii=False, indent=0) + ";\n",
               encoding="utf-8")
print(f"{len(nodes)} nodes -> {OUT}  ({OUT.stat().st_size/1024:.0f} KB)")
withdetail = sum(1 for n in nodes if n["nPoints"])
print(f"  {withdetail} carry point-by-point detail in the full app")
sync_spine_tags()
