"""Pull the questions for nodes that have a spine, into the 速通简洁版.

    python tools/build-lite-questions.py

Only the spined nodes, on purpose. The full app's question set is large and the lite
app is meant to open fast on a tablet; there is also no point shipping questions for
a section whose thread has not been written yet. Re-run whenever a spine is added.

Reads the node `quiz` arrays plus the bank registry (window.BIOCHEM.bank), exactly as
biochemie_pro merges them, so a question that was rewritten there is not re-edited here.
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOPICS = ROOT / "tools" / "topics.json"
LITE = ROOT / "biochemie_lite"
OUT = LITE / "data" / "questions.js"

if not TOPICS.exists():
    sys.exit("run tools/dump-topics.py first")
topics = json.loads(TOPICS.read_text(encoding="utf-8"))

# which nodes have a spine? read the ids straight out of the spine files
spined = set()
for f in sorted((LITE / "data").glob("spine_*.js")):
    for m in re.finditer(r'BIOLITE_SPINE\["([^"]+)"\]', f.read_text(encoding="utf-8")):
        spined.add(m.group(1))
if not spined:
    sys.exit("no spines found in biochemie_lite/data/spine_*.js")

# the bank lives in its own registry keyed by node id; dump-topics only captures
# window.BIOCHEM.topics, so read the bank files directly for the ids we need
bank = {}
for f in sorted((ROOT / "biochemie_pro" / "data").glob("bank_*.js")):
    txt = f.read_text(encoding="utf-8")
    for nid in spined:
        if f'"{nid}"' in txt or f"'{nid}'" in txt:
            bank.setdefault(nid, True)

out, counts = {}, {}
for t in topics:
    if t["id"] not in spined:
        continue
    qs = list(t.get("quiz") or [])
    if qs:
        out[t["id"]] = qs
        counts[t["id"]] = len(qs)

OUT.parent.mkdir(parents=True, exist_ok=True)
header = (
    "/* Questions for the spined nodes. GENERATED by tools/build-lite-questions.py\n"
    "   from biochemie_pro's own data — do not edit by hand; edit them there and\n"
    "   re-run, so the two apps never disagree about an answer.\n\n"
    "   Only nodes that have a spine are included: the lite app has to open fast on a\n"
    "   tablet, and a question set for a section whose thread is not written yet is\n"
    "   weight with no use. Re-run after adding a spine. */\n"
    "window.BIOLITE_Q = ")
OUT.write_text(header + json.dumps(out, ensure_ascii=False, indent=0) + ";\n", encoding="utf-8")

total = sum(counts.values())
print(f"{len(spined)} spined node(s): {', '.join(sorted(spined))}")
print(f"{total} questions -> {OUT}  ({OUT.stat().st_size/1024:.0f} KB)")
for k, v in sorted(counts.items()):
    print(f"   {k}: {v}")
# A `key:<topic>` spine is a merged topic, not a node, so it never has questions of
# its own — the app pools them from the sections the topic covers. Reporting those as
# missing sent one agent looking for a defect that was not there.
missing = sorted(k for k in (spined - set(out)) if not k.startswith("key:"))
merged = sorted(k for k in spined if k.startswith("key:"))
if missing:
    print(f"   no questions in the full app for: {', '.join(missing)}")
if merged:
    print(f"   {len(merged)} merged topic(s) pool their sections' questions at runtime")
