"""Render many nodes across worker processes, resumably.

    python tools/render-audio-bulk.py --plan                       # what it would do
    python tools/render-audio-bulk.py --langs en,zh --workers 10
    python tools/render-audio-bulk.py --exclude coverageNote --max-chars 3000

tools/render-audio.py does one node at a time in one process, which is right for a
handful of nodes and wrong for 10,000 clips: measured on this machine Kokoro runs at
about 1.7x realtime in a single process, so the whole corpus is ~39 CPU-hours.

Three things this adds:

RESUMABLE. Each worker writes its clips and reports back; the manifest is rewritten
after every batch. Killing it and starting again re-renders nothing, because a key
already in the manifest is skipped. That matters at this length -- the run is hours,
and a laptop lid closing should not cost the lot.

ONE MODEL PER WORKER. Loading kokoro-v1.0.onnx takes seconds and ~400 MB; doing it
per clip would dominate the run. Each worker loads once and streams jobs from a queue.

SCOPE BY FIELD, NOT BY LUCK. --exclude takes the `where` labels recorded by
dump-speakables.py. The default excludes coverageNote: the five longest clips in the
corpus are 6,500-7,700 character coverage notes, which are editorial notes about what
was read off the scan. Rendering them costs a fifth of the total bytes and nobody
listens to one.
"""
import argparse, json, multiprocessing as mp, os, pathlib, re, subprocess, sys, time

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

AUDIO = ROOT / "biochemie_pro" / "audio"
MANIFEST = AUDIO / "manifest.js"
MODEL_DIR = pathlib.Path(os.environ.get("KOKORO_DIR", ROOT / ".kokoro"))

def load_key_fns():
    import importlib.util
    spec = importlib.util.spec_from_file_location("ra", ROOT / "tools" / "render-audio.py")
    ra = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ra)
    return ra

def read_manifest():
    if not MANIFEST.exists():
        return {}
    raw = MANIFEST.read_text(encoding="utf-8")
    m = re.search(r"=\s*(\{.*\});?\s*$", raw, re.S)
    return json.loads(m.group(1)) if m else {}

def write_manifest(man):
    header = (
        "/* Pre-rendered reading audio. Generated by tools/render-audio*.py --\n"
        "   do not edit by hand.\n\n"
        "   Maps fnv1a32(lang + U+001F + normalised text) to a file in this folder.\n"
        "   The app hashes the same text it would have spoken and plays the file if\n"
        "   there is one, otherwise it falls back to the browser's own voice -- which\n"
        "   is what every clip-less button, and every Czech one, does anyway.\n\n"
        "   Voice: Kokoro-82M (Apache-2.0), British female / Mandarin. The licence is\n"
        "   why this audio can be committed and served publicly. */\n"
        "window.BIOPRO_AUDIO = ")
    tmp = MANIFEST.with_suffix(".js.tmp")
    tmp.write_text(header + json.dumps(man, indent=0, sort_keys=True) + ";\n", encoding="utf-8")
    tmp.replace(MANIFEST)      # atomic: a half-written manifest breaks every lookup

def make_kokoro(threads):
    """One session per worker, with the thread count set explicitly.

    Getting this wrong is expensive and looks like nothing in particular. The first
    bulk run set OMP_NUM_THREADS=2 to stop ten workers oversubscribing 24 logical
    cores; onnxruntime then gave each worker 2 threads, the machine sat at 32% CPU,
    and the ETA came out at 35 hours. Threads are a session option, not an
    environment variable, so they are set here and workers x threads is kept near
    the core count."""
    import onnxruntime as ort
    from kokoro_onnx import Kokoro
    so = ort.SessionOptions()
    so.intra_op_num_threads = threads
    so.inter_op_num_threads = 1
    model = str(MODEL_DIR / "kokoro-v1.0.onnx")
    providers = ["CPUExecutionProvider"]
    if "CUDAExecutionProvider" in ort.get_available_providers():
        providers = ["CUDAExecutionProvider", "CPUExecutionProvider"]
    try:
        sess = ort.InferenceSession(model, sess_options=so, providers=providers)
    except Exception:
        sess = ort.InferenceSession(model, sess_options=so, providers=["CPUExecutionProvider"])
    return Kokoro.from_session(sess, str(MODEL_DIR / "voices-v1.0.bin"))

def worker(jobs, results, voice_en, voice_zh, bitrate, threads):
    import soundfile as sf
    import imageio_ffmpeg
    ff = imageio_ffmpeg.get_ffmpeg_exe()
    kok = make_kokoro(threads)
    while True:
        job = jobs.get()
        if job is None:
            break
        key, text, lang = job
        try:
            short = lang.split("-")[0]
            samples, rate = kok.create(
                text,
                voice=voice_zh if short == "zh" else voice_en,
                speed=1.0,
                lang="cmn" if short == "zh" else "en-gb")
            wav = AUDIO / (key + ".wav")
            out = AUDIO / (key + ".m4a")
            sf.write(wav, samples, rate)
            subprocess.run([ff, "-y", "-loglevel", "error", "-i", str(wav),
                            "-c:a", "aac", "-b:a", bitrate, "-ar", "24000",
                            "-ac", "1", str(out)], check=True)
            wav.unlink(missing_ok=True)
            results.put((key, out.name, out.stat().st_size, len(samples) / rate, None))
        except Exception as e:                       # one bad clip must not stop the run
            results.put((key, None, 0, 0, f"{type(e).__name__}: {e}"))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--speakables", default=str(ROOT / "tools" / "speakables.json"))
    ap.add_argument("--langs", default="en,zh")
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--threads", type=int, default=0,
                    help="onnxruntime threads per worker; 0 = cores // workers")
    ap.add_argument("--bitrate", default="32k",
                    help="32k is transparent enough for speech and halves the corpus")
    ap.add_argument("--voice-en", default="bf_emma")
    ap.add_argument("--voice-zh", default="zf_xiaoxiao")
    ap.add_argument("--exclude", default="coverageNote",
                    help="comma list of `where` labels to skip")
    ap.add_argument("--only", default="", help="comma list of `where` labels to keep")
    ap.add_argument("--nodes", default="", help="comma list of node ids")
    ap.add_argument("--max-chars", type=int, default=0,
                    help="skip clips longer than this (0 = no cap)")
    ap.add_argument("--plan", action="store_true", help="report and exit")
    ap.add_argument("--prune", action="store_true",
                    help="delete clips whose text no longer exists in the app")
    args = ap.parse_args()

    AUDIO.mkdir(exist_ok=True)
    ra = load_key_fns()
    man = read_manifest()
    rows = json.loads(pathlib.Path(args.speakables).read_text(encoding="utf-8"))

    langs = set(args.langs.split(","))
    excl = set(x for x in args.exclude.split(",") if x)
    only = set(x for x in args.only.split(",") if x)
    nodes = set(x for x in args.nodes.split(",") if x)

    if args.prune:
        # Editing the prose changes its hash, so the old clip stops being looked up
        # and just sits there. Nothing breaks -- the button falls back to the browser
        # voice until the new text is rendered -- but the files accumulate. Prune
        # compares the manifest against every key the app can currently ask for.
        live = {ra.clip_key(r["text"], r["lang"]) for r in rows}
        dead = [k for k in man if k not in live]
        freed = 0
        for k in dead:
            f = AUDIO / man[k]
            if f.exists():
                freed += f.stat().st_size
                f.unlink()
            del man[k]
        write_manifest(man)
        print(f"pruned {len(dead)} orphaned clips, freed {freed/1024/1024:.1f} MB")
        print(f"manifest now holds {len(man)} clips")
        return 0

    jobs, skipped = {}, {"lang": 0, "where": 0, "node": 0, "long": 0, "done": 0}
    for r in rows:
        if r["lang"].split("-")[0] not in langs: skipped["lang"] += 1; continue
        w = r.get("where", "other")
        if only and w not in only: skipped["where"] += 1; continue
        if w in excl: skipped["where"] += 1; continue
        if nodes and r["id"] not in nodes: skipped["node"] += 1; continue
        if args.max_chars and len(r["text"]) > args.max_chars: skipped["long"] += 1; continue
        k = ra.clip_key(r["text"], r["lang"])
        if k in man: skipped["done"] += 1; continue
        jobs.setdefault(k, (ra.norm(r["text"]), r["lang"]))

    threads = args.threads or max(1, (os.cpu_count() or 8) // max(1, args.workers))
    chars = sum(len(t) for t, _ in jobs.values())
    # 41.7 s per 1000 characters is what this machine measured for ONE process using
    # every thread. Splitting it across workers does not add throughput -- the
    # machine was already saturated -- so the estimate does NOT divide by workers.
    # Workers exist to keep it saturated despite ffmpeg and I/O gaps, not to multiply it.
    est_h = chars / 1000 * 41.7 / 3600
    print(f"to render : {len(jobs)} clips, {chars:,} chars")
    print(f"skipped   : {skipped}")
    print(f"workers   : {args.workers} x {threads} threads (of {os.cpu_count()} logical)")
    print(f"estimate  : ~{est_h:.1f} h at {args.bitrate}, from a measured 41.7 s/1000 chars")
    if args.plan or not jobs:
        return 0

    ctx = mp.get_context("spawn")
    q, res = ctx.Queue(), ctx.Queue()
    procs = [ctx.Process(target=worker,
                         args=(q, res, args.voice_en, args.voice_zh, args.bitrate, threads),
                         daemon=True) for _ in range(args.workers)]
    for p in procs: p.start()
    for k, (t, l) in jobs.items(): q.put((k, t, l))
    for _ in procs: q.put(None)

    t0, done, bytes_, secs, errs = time.time(), 0, 0, 0.0, []
    total = len(jobs)
    while done < total:
        key, name, size, dur, err = res.get()
        done += 1
        if err:
            errs.append((key, err))
        else:
            man[key] = name; bytes_ += size; secs += dur
        if done % 25 == 0 or done == total:
            write_manifest(man)
            el = time.time() - t0
            rate = done / el
            print(f"  {done}/{total}  {bytes_/1024/1024:6.0f} MB  {secs/3600:5.1f} h audio  "
                  f"{el/60:5.1f} min elapsed  ETA {((total-done)/rate)/60:6.1f} min  "
                  f"errors {len(errs)}", flush=True)
    write_manifest(man)
    for p in procs: p.join(timeout=10)

    print(f"\ndone: {done - len(errs)} clips, {bytes_/1024/1024:.0f} MB, "
          f"{secs/3600:.1f} h audio, {(time.time()-t0)/60:.0f} min")
    print(f"manifest now holds {len(man)} clips")
    for k, e in errs[:20]:
        print("  ERROR", k, e)
    return 1 if errs else 0

if __name__ == "__main__":
    sys.exit(main())
