"""Pre-render the 速通简洁版 spines to audio.

    python tools/render-spine-audio.py --plan
    python tools/render-spine-audio.py --langs en,zh --workers 6

WHY A SECOND RENDERER
tools/render-audio.py harvests what to say from biochemie_pro's rendered DOM, which
is exact for that app and useless for this one: the lite app's text is the spine, and
the spine is not in the full app at all. The text here comes straight out of the
spine files, so no browser is needed.

Everything else is shared on purpose — the same key scheme (fnv1a32 of lang + U+001F +
normalised text), the same Kokoro voices, the same .m4a. If the two ever disagree
about a key, every lookup misses SILENTLY and both apps just fall back to the browser
voice, so clip_key is imported from render-audio.py rather than reimplemented.

The lite app reads `window.BIOLITE_AUDIO`, not `window.BIOPRO_AUDIO`: the two apps
have separate audio folders because they say different things, and a shared global
would have one overwrite the other depending on script order.
"""
import argparse, importlib.util, json, multiprocessing as mp, os, pathlib, re, subprocess, sys, time

ROOT = pathlib.Path(__file__).resolve().parent.parent
LITE = ROOT / "biochemie_lite"
AUDIO = LITE / "audio"
MANIFEST = AUDIO / "manifest.js"
MODEL_DIR = pathlib.Path(os.environ.get("KOKORO_DIR", ROOT / ".kokoro"))

spec = importlib.util.spec_from_file_location("ra", ROOT / "tools" / "render-audio.py")
ra = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ra)

spec2 = importlib.util.spec_from_file_location("cs", ROOT / "tools" / "check-spine.py")
cs = importlib.util.module_from_spec(spec2)
spec2.loader.exec_module(cs)


def spoken_text(sp):
    """Every string the lite app puts behind a 🔊, in reading order.

    Mirrors the sayBtn / sayPairBtn call sites in biochemie_lite/app.js: the node
    title, each step in both languages, and each glossary term."""
    out = []
    if sp.get("nodeTitle_en"):
        out.append((sp["nodeTitle_en"], "en-US"))
    for s in sp.get("steps") or []:
        if s.get("en"): out.append((s["en"], "en-US"))
        if s.get("cn"): out.append((s["cn"], "zh-CN"))
    for t in sp.get("terms") or []:
        if t.get("en"): out.append((t["en"], "en-US"))
        if t.get("def_en"): out.append((t["def_en"], "en-US"))
        if t.get("def_cn"): out.append((t["def_cn"], "zh-CN"))
    return out


def read_manifest():
    if not MANIFEST.exists():
        return {}
    m = re.search(r"=\s*(\{.*\});?\s*$", MANIFEST.read_text(encoding="utf-8"), re.S)
    return json.loads(m.group(1)) if m else {}


def write_manifest(man):
    header = (
        "/* Pre-rendered reading audio for the 速通简洁版. Generated by\n"
        "   tools/render-spine-audio.py — do not edit by hand.\n\n"
        "   Maps fnv1a32(lang + U+001F + normalised text) to a file in this folder,\n"
        "   the same scheme the full app uses. The app hashes the text it would have\n"
        "   spoken and plays the file if there is one; otherwise it falls back to the\n"
        "   browser's own voice, which is what every clip-less button does anyway.\n\n"
        "   Separate global from the full app's on purpose: the two say different\n"
        "   things, and one shared name would have whichever loaded last win.\n\n"
        "   Voice: Kokoro-82M (Apache-2.0). That licence is why this audio can be\n"
        "   committed and served publicly. */\n"
        "window.BIOLITE_AUDIO = ")
    tmp = MANIFEST.with_suffix(".js.tmp")
    tmp.write_text(header + json.dumps(man, indent=0, sort_keys=True) + ";\n", encoding="utf-8")
    tmp.replace(MANIFEST)      # atomic: a half-written manifest breaks every lookup


def worker(jobs, results, voice_en, voice_zh, bitrate, threads):
    import onnxruntime as ort
    from kokoro_onnx import Kokoro
    import soundfile as sf
    import imageio_ffmpeg
    ff = imageio_ffmpeg.get_ffmpeg_exe()
    so = ort.SessionOptions()
    so.intra_op_num_threads = threads
    so.inter_op_num_threads = 1
    sess = ort.InferenceSession(str(MODEL_DIR / "kokoro-v1.0.onnx"),
                                sess_options=so, providers=["CPUExecutionProvider"])
    kok = Kokoro.from_session(sess, str(MODEL_DIR / "voices-v1.0.bin"))
    while True:
        job = jobs.get()
        if job is None:
            break
        key, text, lang = job
        try:
            short = lang.split("-")[0]
            samples, rate = kok.create(
                text, voice=voice_zh if short == "zh" else voice_en, speed=1.0,
                # espeak-ng calls Mandarin "cmn"; "zh" is rejected outright
                lang="cmn" if short == "zh" else "en-gb")
            wav, out = AUDIO / (key + ".wav"), AUDIO / (key + ".m4a")
            sf.write(wav, samples, rate)
            subprocess.run([ff, "-y", "-loglevel", "error", "-i", str(wav),
                            "-c:a", "aac", "-b:a", bitrate, "-ar", "24000",
                            "-ac", "1", str(out)], check=True)
            wav.unlink(missing_ok=True)
            results.put((key, out.name, out.stat().st_size, len(samples) / rate, None))
        except Exception as e:
            results.put((key, None, 0, 0, f"{type(e).__name__}: {e}"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("nodes", nargs="*")
    ap.add_argument("--langs", default="en,zh")
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--threads", type=int, default=0)
    ap.add_argument("--bitrate", default="32k")
    ap.add_argument("--voice-en", default="bf_emma")
    ap.add_argument("--voice-zh", default="zf_xiaoxiao")
    ap.add_argument("--plan", action="store_true")
    ap.add_argument("--prune", action="store_true",
                    help="delete clips whose text is no longer in any spine")
    args = ap.parse_args()

    AUDIO.mkdir(parents=True, exist_ok=True)
    spines, bad = cs.load_spines()
    for f, nid, e in bad:
        print(f"UNPARSEABLE {f} {nid}: {e}")
    man = read_manifest()
    langs = set(args.langs.split(","))

    pairs = []
    for nid, sp in sorted(spines.items()):
        if args.nodes and nid not in args.nodes:
            continue
        for text, lang in spoken_text(sp):
            if lang.split("-")[0] in langs:
                pairs.append((text, lang))

    if args.prune:
        live = {ra.clip_key(t, l) for nid, sp in spines.items()
                for t, l in spoken_text(sp)}
        dead = [k for k in man if k not in live]
        freed = 0
        for k in dead:
            f = AUDIO / man[k]
            if f.exists():
                freed += f.stat().st_size
                f.unlink()
            del man[k]
        write_manifest(man)
        print(f"pruned {len(dead)} orphaned clips, freed {freed/1024/1024:.1f} MB")
        return 0

    jobs = {}
    for text, lang in pairs:
        k = ra.clip_key(text, lang)
        if k not in man and k not in jobs:
            jobs[k] = (ra.norm(text), lang)

    chars = sum(len(t) for t, _ in jobs.values())
    threads = args.threads or max(1, (os.cpu_count() or 8) // max(1, args.workers))
    # 41.7 s per 1000 characters is what this machine measured for one process using
    # every thread. Workers keep it saturated across ffmpeg and I/O gaps; they do not
    # multiply throughput, so the estimate does not divide by them.
    print(f"{len(spines)} spine(s), {len(pairs)} spoken string(s) -> {len(jobs)} new clip(s)")
    print(f"workers   : {args.workers} x {threads} threads")
    print(f"estimate  : ~{chars/1000*41.7/60:.0f} min at {args.bitrate}")
    if args.plan or not jobs:
        return 0

    ctx = mp.get_context("spawn")
    q, res = ctx.Queue(), ctx.Queue()
    procs = [ctx.Process(target=worker,
                         args=(q, res, args.voice_en, args.voice_zh, args.bitrate, threads),
                         daemon=True) for _ in range(args.workers)]
    for p in procs: p.start()
    for k, (t, l) in jobs.items(): q.put((k, t, l))
    for _ in procs: q.put(None)

    t0, done, total, bytes_, secs, errs = time.time(), 0, len(jobs), 0, 0.0, []
    while done < total:
        key, name, size, dur, err = res.get()
        done += 1
        if err:
            errs.append((key, err))
        else:
            man[key] = name; bytes_ += size; secs += dur
        if done % 10 == 0 or done == total:
            write_manifest(man)
            el = time.time() - t0
            print(f"  {done}/{total}  {bytes_/1024/1024:5.1f} MB  {secs/60:5.1f} min audio  "
                  f"{el/60:5.1f} min elapsed  errors {len(errs)}", flush=True)
    write_manifest(man)
    for p in procs: p.join(timeout=10)
    print(f"\ndone: {done-len(errs)} clips, {bytes_/1024/1024:.1f} MB, {secs/60:.1f} min audio")
    print(f"manifest now holds {len(man)} clips")
    for k, e in errs[:10]:
        print("  ERROR", k, e)
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
